package com.surya;

/**
 * 
 * @author Arthanarisamy
 */
public interface ServerConstants {

	String DEFAULT_APP_ID = "com.appzillon.web";
	String YES = "Y";
	String NO = "N";
	String MESSAGE_HEADER = "appzillonHeader";
	String MESSAGE_BODY = "appzillonBody";
	String MESSAGE_ERROR = "appzillonErrors";
	String MESSAGE_SAFE = "appzillonSafe";
	String MESSAGE_HEADER_APP_ID = "appId";
	String MESSAGE_HEADER_SESSION_ID = "sessionId";
	String MESSAGE_HEADER_REQUEST_KEY = "requestKey";
	String MESSAGE_HEADER_USER_ID = "userId";
	String MESSAGE_HEADER_DEVICE_ID = "deviceId";
	String MESSAGE_HEADER_SCREEN_ID = "screenId";
	String MESSAGE_HEADER_REQ_REF_ID = "reqRefId";
	String MESSAGE_HEADER_INTERFACE_ID = "interfaceId";
	String MESSAGE_HEADER_SERVICE_TYPE = "serviceType";
	String MESSAGE_HEADER_STATUS = "status";
	String MESSAGE_HEADER_ASYNCH = "async";
	String MESSAGE_HEADER_ERROR_CODE = "errorCode";
	String MESSAGE_HEADER_ERROR_MESSAGE = "errorMessage";
	String MESSAGE_HEADER_SIGNATURE = "signature";
	String ENFORCE_SIGN_VALIDATION = "enforceSignValidation";
	String INTERFACE_CATEGORY_EXTERNAL = "EXTERNAL";
	String INTERFACE_CATEGORY_INTERNAL = "INTERNAL";
	String INTERFACE_TYPE_SMS = "SMS";
	String INTERFACE_TYPE_NOTIFICATIONS = "NOTIFICATIONS";
	String INTERFACE_TYPE_APPZILLON_WORKFLOW = "APPZILLONWORKFLOW";
	String INTERFACE_TYPE_WORKFLOW = "WORKFLOW";
	String INTERFACE_TYPE_INTERFACE = "INTERFACE";
	String INTERFACE_TYPE_LOV = "LOV";
	String INTERFACE_TYPE_FETCHINTERFACELIST = "fetchInterfaceList";
	String INTERFACE_SESSION_REQ_YES = "Y";
	String INTERFACE_SESSION_REQ_NO = "N";
	String INTERFACE_ID_AUTHENTICATION = "appzillonAuthenticationRequest";
	String INTERFACE_ID_CHANGE_PASSWORD = "appzillonChangePassword";
	String INTERFACE_ID_DEVICE_REGISTRATION = "appzillonNotificationRegistration";
	String INTERFACE_ID_UPLOAD_FILE = "appzillonUploadFile";
	String INTERFACE_ID_UPLOAD_FILE_WS = "appzillonUploadFileWS";
	String INTERFACE_ID_UPLOAD_FILE_AUTH = "appzillonUploadFileAuth";
	String INTERFACE_ID_CACHE_FLUSH = "appzillonFlushCacheReq";
	String INTERFACE_ID_RE_LOGIN = "appzillonReLoginRequest";
	String INTERFACE_ID_AUDIT_LOG = "appzillonAuditLog";
	String INTERFACE_ID_APP_USAGE_REPORT = "appzillonAppUsageReport";
	String INTERFACE_ID_CREATE_DEVICE = "appzillonCreateDevice";
	String INTERFACE_ID_CREATE_GROUP = "appzillonCreateGroup";
	String INTERFACE_ID_CREATE_ROLE_MASTER = "appzillonCreateRoleMaster";
	String INTERFACE_ID_CREATE_SCREEN = "appzillonCreateScreen";
	String INTERFACE_ID_CREATE_USER = "appzillonCreateUser";
	String INTERFACE_ID_USER_REGISTER = "appzillonUserRegistration";
	String INTERFACE_ID_USER_AUTHORIZATION= "appzillonUserAuthorization";
	String INTERFACE_ID_DELETE_DEVICE = "appzillonDeleteDevice";
	String INTERFACE_ID_DELETE_FILE = "appzillonDeleteFile";
	String INTERFACE_ID_DELETE_GROUP = "appzillonDeleteGroup";
	String INTERFACE_ID_DELETE_SCREEN = "appzillonDeleteScreen";
	String INTERFACE_ID_FILE_PUSH_SERVICE = "appzillonFilePushService";
	String INTERFACE_ID_FILE_PUSH_SERVICE_AUTH = "appzillonFilePushServiceAuth";
	String INTERFACE_ID_FILE_PUSH_SERVICE_WS = "appzillonFilePushServiceWS";
	String INTERFACE_ID_GET_GROUP_DETAIL = "appzillonGetGroupDetail";
	String INTERFACE_ID_GET_REQ_RESP = "appzillonGetReqResp";
	String INTERFACE_ID_INTF_AUTH_REQ = "appzillonInterfaceAuthRequest";
	String INTERFACE_ID_SCREEN_AUTH_REQ = "appzillonScreenAuthRequest";
	String INTERFACE_ID_FETCH_PRIVILEGE_SERVICE = "appzillonFetchPrivilegeService";// "appzillonAuthorizationService";
	String INTERFACE_ID_LOGIN_REPORT = "appzillonLoginReport";
	String INTERFACE_ID_NOTIFICATION_APP_DETAIL = "appzillonNotificationAppDetail";
	String INTERFACE_ID_PUSH_NOTIFICATION = "appzillonPushNotification";
	String INTERFACE_ID_SEARCH_DEVICE = "appzillonSearchDevice";
	String INTERFACE_ID_SEARCH_FILE = "appzillonSearchFile";
	String INTERFACE_ID_SEARCH_GROUP = "appzillonSearchGroup";
	String INTERFACE_ID_SEARCH_SCREEN = "appzillonSearchScreen";
	String INTERFACE_ID_SEARCH_TXN_LOG = "appzillonSearchTxnLogging";
	String INTERFACE_ID_UPDATE_DEVICE = "appzillonUpdateDevice";
	String INTERFACE_ID_UPDATE_GROUP = "appzillonUpdateGroup";
	String INTERFACE_ID_UPDATE_SCREEN = "appzillonUpdateScreen";
	String INTERFACE_ID_DECRYPT = "appzillonDecrypt";
	String INTERFACE_ID_LOGGING_REQ = "appzillonLoggingRequest";
	String INTERFACE_ID_WF_DASHBOARD_QUERY = "appzillonWorkflowDashboardQuery";
	String INTERFACE_ID_WF_PERSIST = "appzillonWorkflowPersist";
	String INTERFACE_ID_WF_QUERY = "appzillonWorkflowQuery";
	String INTERFACE_ID_WF_QUERY_DB = "appzillonWorkflowQueryDb";
	String INTERFACE_ID_WF_QUERY_REQ = "appzillonWorkflowQueryRequest";
	String INTERFACE_ID_CREATE_PASSWORD_RULES = "appzillonCreatePasswordRules";
	String INTERFACE_ID_DELETE_PASSWORD_RULES = "appzillonDeletePasswordRules";
	String INTERFACE_ID_GET_PASSWORD_RULES = "appzillonGetPasswordRules";
	String INTERFACE_ID_GET_PASSWORD_BY_RULES = "appzillonGetPasswordByRules";
	String INTERFACE_ID_UPDATE_PASSWORD_RULES = "appzillonUpdatePasswordRules";
	String INTERFACE_ID_UPDATE_USER = "appzillonUpdateUser";
	String INTERFACE_ID_DELETE_USER = "appzillonDeleteUser";
	String INTERFACE_ID_SEARCH_USER = "appzillonSearchUser";
	String INTERFACE_ID_GET_ROLES_APPID_USERID = "appzillonGetRolesByAppIDUserID";
	String INTERFACE_ID_GET_ROLES_APPID = "appzillonGetRolesByAppID";
	String INTERFACE_ID_PASSWORD_RESET = "appzillonPasswordReset";
	String INTERFACE_ID_FORGOT_PASSWORD = "appzillonForgotPassword";
	String INTERFACE_ID_UNLOCK_USER = "appzillonUnlockUser";
	String INTERFACE_ID_GET_USER = "appzillonGetUser";
	String INTERFACE_ID_UPDATE_ROLE_MASTER = "appzillonUpdateRoleMaster";
	String INTERFACE_ID_DELETE_ROLE_MASTER = "appzillonDeleteRoleMaster";
	String INTERFACE_ID_GET_ROLE_MASTER = "appzillonGetRoleMaster";
	String INTERFACE_ID_GET_SCREENS_INTF_APPID = "appzillonGetScreensIntfByAppID";
	String INTERFACE_ID_GET_SCREENS_INTF_APPID_ROLEID = "appzillonGetIntfScrByAppIDRoleID";
	String INTERFACE_ID_SEARCH_INTF_MASTER = "appzillonSearchIntfMaster";
	String INTERFACE_ID_CREATE_INTF_MASTER = "appzillonCreateIntfMaster";
	String INTERFACE_ID_DELETE_INTF_MASTER = "appzillonDeleteIntfMaster";
	String INTERFACE_ID_UPDATE_INTF_MASTER = "appzillonUpdateIntfMaster";
	String INTERFACE_ID_LOGOUT = "appzillonLogoutRequest";
	String INTERFACE_ID_LOV = "appzillonLOVReq";
	String INTERFACE_ID_NOTLOV = "appzillonNotLOVReq";
	// String INTERFACE_ID_CREATE_PASSWORD = "appzillonCreatePassword";
	String INTERFACE_ID_PASSWORD_VALIDATE = "appzillonPasswordValidate";
	String INTERFACE_ID_MAIL_REQ = "appzillonMailRequest";
	String INTERFACE_ID_JMSRESFETCHREQ = "JMSRespFetchReq";
	String INTERFACE_ID_VALIDATE_AND_PROCESSIFACE = "appzillonValNProcessIface";
	String INTERFACE_ID_MSG_STATS = "appzillonMessageStatistics";
	String INTERFACE_ID_DASHBOARD = "appzillonDashBoard";
	String INTERFACE_ID_CUSTOMER = "appzillonCustomer";
	String INTERFACE_ID_CUSTOMER_LOCATION = "appzillonCustomerLocation";
	String INTERFACE_ID_CUSTOMER_DETAILS = "appzillonCustomerDetails";
	//workflow constants
	String INTERFACE_ID_WORKFLOW_START = "workflowStart";
	String INTERFACE_ID_WORKFLOW_NEXT = "workflowNext";
	String INTERFACE_ID_WORKFLOW_PREV = "workflowPrev";
	String INTERFACE_ID_WORKFLOW_SAVE = "workflowSave";
	String INTERFACE_ID_WORKFLOW_TERMINATE = "workflowTerminate";
	String INTERFACE_ID_WORKFLOW_QUERY = "workflowQuery";
	String INTERFACE_ID_WORKFLOW_ASSIGN = "workflowAssign";
	String INTERFACE_ID_WORKFLOW_REASSIGN = "workflowReassign";
	String INTERFACE_ID_WORKFLOW_ACQUIRE = "workflowAcquire";
	String INTERFACE_ID_WORKFLOW_UNASSIGN = "workflowUnassign";
	String LOV_QUERY_ID = "lovid";
	String LOV_QUERY_TYPE_HQL = "HQL";
	String LOV_FILTER_VAR_COLS = "filterColumns";
	String LOV_FILTER_VARIABLES_COLS = "filtervariableCols";
	String LOV_FILTER_VARIABLES_VALUES = "filtervariablesValues";
	String LOV_BIND_VAR_DATA_TYPE = "bindVarDataType";
	String LOV_BIND_VARIABLES_DATA_TYPE = "bindvariablesDataTypes";
	String LOV_BIND_VARIABLES_VALUES = "bindvariablesValues";
	String LOV_BIND_VAR_COLS = "bindVarColumns";
	String LOV_QUERY_TYPE = "queryType";
	String LOV_ORDER_BY_COLS = "orderByColumns";
	String LOV_ORDER_BY_TYPE = "orderByType";
	String LOV_QUERY_STRING = "queryString";
	String LOV_QUERY_RESULT = "queryresult";
	String LOV_DATA_SOURCE = "dataSource";
	String LOV_SESSION_REQD = "sessionReqd";
	String LOV_QUERY_TYPE_SQL = "SQL";
	String LOV_QUERY_CURRENT_PAGE_NO = "currpage";
	String LOV_QUERY_ELEMENT_ID = "elementid";
	String LOV_QUERY_RESULT_SET_COLUMN_NAMES = "resultfieldcolumnstr";
	String LOV_QUERY_RESULT_SET_COLUMN_DATA_TYPES = "resultfielddatatypestr";
	String LOV_QUERY_RECORDS_PER_PAGE = "pagesize";
	String SEPARATOR_PIPE = "|";
	String LOV_QUERY_RESULT_NODE_NAME = "result";
	String LOV_QUERY_RESULT_NODE_ARRAY_NAME = "resultset";
	String LOV_QUERY_TOTAL_NO_OF_PAGES = "totalpages";
	String LOV_QUERY_OUTER_QUERY = "select * from (";
	String LOV_QUERY_OUTER_QUERY_WHERE_CLAUSE = " ) appzillonLov where ";
	String LOV_QUERY_OUTER_QUERY_ORDER_BY_CLAUSE = " order by ";
	String LOV_QUERY_OUTER_QUERY_END = ") appzillonLov ";
	String WHERE = "where";
	String AND = "and";
	String HIBERNATE_CFG_XML = "hibernate.cfg.xml";
	String LOV_TYPE = "type";
	String LOV_TYPE_STATIC = "SLOV";
	String LOV_QUERY = "query";
	String LOV_BINDCOLUMNS = "bindcolumns";
	String LOV_JNDI = "jndi";
	String LOV_REQOBJ = "slovobj";
	String LOV_QUERY_FILTER_COLUMNS_NAMES = "filterfieldcolumnstr";
	String LOV_QUERY_FILTER_COLUMNS_VALUES = "filterfieldvalstr";
	String LOV_QUERY_BIND_VARIABLES_DATA_TYPES = "bindvariabledatatypestr";
	String LOV_QUERY_BIND_VARIABLES_VALUES = "bindvariablevaluestr";
	String LOV_QUERY_BIND_VARIABLES_COLUMN_NAMES = "bindvariablecolumnstr";
	String LOV_QUERY_ORDER_BY_COLUMN_NAME = "orderbyfieldstr";
	String LOV_QUERY_ORDER_BY_TYPE = "orderbypropertystr";

	String SERVICE_USER_MAINTENANCE = "UserMaintenance";
	String SERVICE_AUTHENTICATION = "AuthenticationService";
	String SERVICE_GENERATE_REPORTS = "GenerateReportService";
	String SERVICE_ROLE_MAINTENANCE = "RoleMaintenanceService";
	String SERVICE_CHANGE_PASSWORD = "ChangePasswordService";
	String SERVICE_SCREEN_MAINTENANCE = "ScreenMaintenanceService";
	String SERVICE_INTERFACE_MAINTENANCE = "InterfaceMaintenance";
	String SERVICE_AUTHORIZATION = "authorizationService";
	String SERVICE_FRAMEWORK = "frameworksService";
	String SERVICE_NOTIFICATION_MAINTENANCE = "NotificationMaintenanceService";
	String SERVICE_PUSH_NOTIFICATION = "NotificationService";
	String SERVICE_FILE = "FileService";
	String SERVICE_AUDIT_LOG = "AuditLogService";


	// String FETCH_SECURITY_PARAMETERS = "FetchSecurityParameters";
	String FETCH_SECURITY_PARAMS = "FetchSecurityParams";
	String UPDATE_LAST_SUCCESS_LOGIN_SERVICE = "UpdateSuccesLastLoginDetails";
	String LOG_TRANSACTION = "LogTransaction";
	String FMW_LOG_TRANSACTION="FmwLogTranscation";
	String UPDATE_REQUESTKEY_SERVICE = "UpdateRequestKeyService";
	String APPZUSERMAINTENANCESERV = "UserMaintenanceService";

	// String APPZSMSAUTHZDEFAULTAUTHREQUEST = "SMSAuthzDefAuthReq";
	String APPZSMSGETUSERROLESREQUEST = "SMSGetUsrRoleReq";
	String APPZISEXISTSINTFID = "isExistInterfaceIdforRoleId";
	String APPZSMSGETSCREENBYFUNID = "getScreenByFunId";

	String CATEGORY = "category";
	String DESCRIPTION = "description";
	String TYPE = "type";
	String SUCCESS = "success";
	String ROLEDESCRIPTION = "roleDesc";
	String FAILURE = "failure";
	String FAIL = "fail";
	String KEYS = "keys";
	String USERLOCKED = "userLocked";
	String USERLOCKEDNO = "N";
	String NOTIFICATION = "notification";
	String NOTIFICATION_PARAMETERS = "params";
	String NOTIFICATION_MESSAGEDATA = "messageData";
	String NOTIFICATION_TITLE = "title";
	String NOTIFICATION_IMAGE_URL = "imageURL";
	String NOTIFICATION_SUBTITLE = "subtitle";
	String NOTIFICATION_CATEGORY = "category";
	String IOS_CONTENT_AVAILABLE = "contentAvailable";
	String TIME = "time";
	String REFNO = "refNo";
	String ANDROID_STATUS = "androidStatus";
	String ANDROID_NOTIFICATION_KEY = "ANDROIDNOTIFKEY";
	String BLACKBERRY_STATUS = "blackBerryStatus";
	String BLACKBERRY10_NOTIFICATION_PWD = "BB10NOTIFPWD";
	String BLACKBERRY10_NOTIFICATION_URL = "BB10NOTIFURL";
	String BLACKBERRY10_NOTIFICATION_APPID = "BB10NOTIFAPPID";
	String IOS_STATUS = "iosStatus";
	String IOS_P12_PASSWORD = "IOSP12PWD";
	String IOS_P12_PATH = "IOSP12PATH";
	String WINDOWS_STATUS = "windowsStatus";
	String DEVICE_TYPE = "deviceType";
	String DEVICE = "device";
	String MODE_OF_CHANNEL = "channel";
	String USERLVL = "userLvl";
	String ANDROID = "ANDROID";
	String WINDOWS = "WINDOWS";
	String IOS = "IOS";
	String JSON_OS = "os";
	String COUNT = "count";
	String PROCESSING_TIME = "processingTime";
	String INTERFACE_DESC = "interfaceDesc"; 
	String TXN_STATUS = "txnStatus";
	String NUM_TRANSACTION = "noOfTransaction";
	String NUM_DISTINCT_LOGINS = "noOfDistinctLogins";
	String TXN_STAT = "txnStat";
	String MIN = "min";
	String MAX = "max";
	String AVG = "avg";
	String TOTAL_TXNS = "totalTxns";
	String DETAIL_SCREEN = "detailScreen";
	String TOTAL_SESSIONS = "totalSessions";
	String SESSIONS = "sessions";
	String TOTAL_INSTALLS = "totalInstalls";
	String INSTALLS = "installs";
	String LOCATION_DETAILS = "locationDetails";
	String USERS = "users";
	String ACTIVE_INACTIVE_USERS = "activeInactiveUsers";
	String INACTIVE_COUNT = "inActiveCount";
	String ACTIVE_COUNT = "activeCount";
	String OPERATION = "operation";
	String ACTIVE_USERS = "activeUsers";
	String INACTIVE_USERS = "inActiveUsers";
	String MIN_SESSION_TIME = "minSessionTime";
	String MAX_SESSION_TIME = "maxSessionTime";
	String AVG_SESSION_TIME = "avgSessionTime";
	String DISTINCT_TXNS = "distinctTxns";
	String LOGINS= "logins";
	String DISTINCT_LOGINS = "distinctLogins";

	//new variables for userDet node 
	String USERDET = "userDet";
	String NAME = "name";
	String ID = "id";
	String USERDET_EXTERNALIDENTIFIER = "extId";

	String LASTNPWDNOTTOUSE = "lastNPwdNotToUse";
	String MAXLEN = "maxLen";
	String MINLEN = "minLen";
	String MINNUMOFNUM = "minNumOfNum";
	String MINNUMOFSLCLCHAR = "minNumOfSpclChar";
	String MINNUMOFUPPCHAR = "minNumOfUppChar";
	String PWDCHANGEFREQ = "pwdChangeFreq";
	String PWDCHANGECOMCHANNEL = "pwdChangeComChannel";
	String PWDSESSIONTIMEOUT = "sessiontimeout";
	String NOOFFAILEDCOUNTS = "nooffailedcounts";
	String SERVICE_TYPE_DEFAULT_AUTHORIZATION = "defaultAuthorization";
	String FAILEDCOUNTTIMEOUT = "failCountTimeout";
	String SERVERTOKEN = "serverToken";
	String PASSWORDCOUNT = "passwordCount";
	String RESTRICTEDSPLCHARS = "restrictSplChar";
	String PWDRSETVALIDATE = "pwdRsetValidate";
	String PWDRSETCOMCHANNEL = "pwdRsetComChannel";
	String PWDRSETACCPTPWD = "pwdRsetAccptPwd";
	String BOTH = "BOTH";
	String PMOBILE = "PMOBILE";
	String PEMAIL = "PEMAIL";
	String PEMAIL_AND_PNOTIFICATION = "email_and_notification";
	String PMOBILE_AND_PEMAIL       = "mobile_and_email";
	String PMOBILE_AND_PNOTIFICATION = "mobile_and_notification";
	String NONE = "NONE";
	// added txn_log_req for security parameter
	String TXNLOGREQ = "transactionLogRequest";
	String PWDCOMCHANNEL = "passwordCommChannel";
	// String SMS= "pwdRsetAccptPwd";MinNumNum

	String APPZCREATEINFMASTERRESPONSE = "appzillonCreateIntfMasterResponse";
	String APPZUPDATEINFMASTERRESPONSE = "appzillonUpdateIntfMasterResponse";
	String APPZDELETEINFMASTERRESPONSE = "appzillonDeleteIntfMasterResponse";
	String APPZSEARCHINFMASTERRESPONSE = "appzillonSearchIntfMasterResponse";
	String APPZCREATEINFMASTERREQUEST = "appzillonCreateIntfMasterRequest";
	String APPZUPDATEINFMASTERREQUEST = "appzillonUpdateIntfMasterRequest";
	String APPZDELETEINFMASTERREQUEST = "appzillonDeleteIntfMasterRequest";
	String APPZSEARCHINFMASTERREQUEST = "appzillonSearchIntfMasterRequest";
	String FETCH_USER_SESSION_REQUEST = "appzillonFetchUserSessionRequest";
	String APPZCLEARUSERSESSIONREQUEST = "appzillonClearUserSessionRequest";

	String APPZILLONGETREQRESPREQUEST = "appzillonGetReqRespRequest";
	String APPZILLONLOGINREPORTREQUEST = "appzillonLoginReportRequest";
	String APPZILLONLOGINREPORTRESPONSE = "appzillonLoginReportResponse";
	String APPZILLONAPPUSAGEREPORTREQUEST = "appzillonAppUsageReportRequest";
	String APPZILLONAPPUSAGEREPORTRESPONSE = "appzillonAppUsageReportResponse";
	String APPZILLONSEARCHTXNLOGGINGRESPONSE = "appzillonSearchTxnLoggingResponse";
	String APPZILLONSEARCHTXNLOGGINGREQUEST = "appzillonSearchTxnLoggingRequest";

	String APPZILLONCREATESCREENREQUEST = "appzillonCreateScreenRequest";
	String APPZILLONCREATESCREENRESPONSE = "appzillonCreateScreenResponse";
	String APPZILLONUPDATESCREENREQUEST = "appzillonUpdateScreenRequest";
	String APPZILLONUPDATESCREENRESPONSE = "appzillonUpdateScreenResponse";
	String APPZILLONDELETESCREENREQUEST = "appzillonDeleteScreenRequest";
	String APPZILLONDELETESCREENRESPONSE = "appzillonDeleteScreenResponse";
	String APPZILLONSEARCHSCREENREQUEST = "appzillonSearchScreenRequest";
	String APPZILLONSEARCHSCREENRESPONSE = "appzillonSearchScreenResponse";
	String UPDATELSTFLRLGNSERVICE = "AppzillonUpdateFailureLastLoginDetails";
	String UNLOCK_UPDATE_FAIL_COUNT = "AppzillonUnlockUpdateFailCount";
	String LOCKUSER = "AppzillonLockUser";
	String FAILURE_ATTEMPTS_LEFT = "attemptsLeft";
	String APPZILLONGETREQRESPRESPONSE = "appzillonGetReqRespResponse";
	String APPZILLONUPDATEJOBDETAILREQUEST = "appzillonUpdateJobDetailRequest";
	String APPZILLONUPDATEJOBDETAILRESPONSE = "appzillonUpdateJobDetailResponse";
	String APPZILLONJOBDETAILSRESPONSE = "appzillonJobDetailsResponse";
	String APPZILLONJOBDETAILRESPONSE = "appzillonJobDetailResponse";
	String APPZILLONJOBEXPRESSIONRESPONSE = "appzillonJobExpressionResponse";
	String APPZILLON_ROOT_DASHBOARD_REQ = "appzillonDashBoardRequest";
	String APPZILLON_ROOT_DASHBOARD_RES = "appzillonDashBoardResponse";
	String APPZILLON_AUDITLOG_REQUEST = "appzillonAuditLogRequest";
	String APPZILLON_AUDITLOG_RESPONSE = "appzillonAuditLogResponse";
	String APPZILLONMSGSTATSREPORTREQUEST = "appzillonMessageStatisticsRequest";
	String APPZILLONMSGSTATSREPORTRSPONSE = "appzillonMessageStatisticsResponse";
	String APPZILLON_ROOT_CUSTOMER_REQ = "appzillonCustomerRequest";
	String APPZILLON_ROOT_CUSTOMER_RES = "appzillonCustomerResponse";
	String APPZILLON_ROOT_CUSTOMER_LOC_REQ = "appzillonCustomerLocRequest";
	String APPZILLON_ROOT_CUSTOMER_LOC_RES = "appzillonCustomerLocResponse";
	String APPZILLON_ROOT_CUSTOMER_DETAILS_REQ = "appzillonCustomerDetailsRequest";
	String APPZILLON_ROOT_CUSTOMER_DETAILS_RES = "appzillonCustomerDetailsResponse";

	String SCREENDESCRIPTION = "screenDesc";
	String DBPIN = "dbpin";

	String APPZILLON_DATE_FORMAT = "yyyy-MM-dd";
	String DATE_FORMAT = "dd/MM/yyyy";
	String NOTIFICATION_OS_VERSION = "osVersion";
	String NOTIFICATION_GROUP_ID = "groupId";
	String NOTIFICATION_GROUP_ID_MULTIPLE = "groupIds";
	String NOTIFICATION_OS_ID_MULTIPLE = "osIds";
	String NOTIFICATION_OS_ID = "osId";
	String NOTIFICATION_REGISTRATION_ID = "regId";
	String NOTIFICATION_REGISTRATION_IDS_MULTIPLE = "nfRegIds";
	String NOTIFICATION_DEVICE_NAME = "deviceName";
	String ADDR1 = "addr1";
	String ADDR2 = "addr2";
	String ADDR3 = "addr3";
	String ADDR4 = "addr4";
	String EML1 = "email1";
	String EML2 = "email2";
	String PHNO1 = "phone1";
	String PHNO2 = "phone2";
	String DATE = "date";
	String NOOFLOGINS = "noOfLogins";
	String DATE_OF_BIRTH = "dateOfBirth";

	String LOGINTIME = "loginTime";
	String LAST_REQUEST_TIME = "lastRequestTime";
	String LOGINSTATUS = "loginStatus";
	String CREATETS = "createTs";
	String PIN_CHANGE_TS = "pinChangeTs";
	String USER_LOCK_TS = "userLockTs";
	String CREATEUSERID = "createUserId";
	String REQUESTHEADER = "requestHeader";
	String VERSIONNO = "versionNo";
	String USERNAME = "userName";
	String CREATE = "create";
	String UPDATE = "update";
	String CANPROCEED = "canProceed";
	String LAST_LOGIN = "lastLogin";
	String HASHKEY1 = "hashKey1";
	String HASHKEY2 = "hashKey2";
	String SYSDATE = "sysDate";

	String ROLEID = "roleId";
	String EXTERNALIDENTIFIER = "extIdentifier";
	String MOBILE_NUMBER = "mobileNum";
	String USER_LANAGUAGE = "language";
	String USER_PHONE1 = "phone1";
	String APPZILLONSIMULATOR = "SIMULATOR";
	String WEB = "WEB";

	String PIN = "pwd";
	String NEWPASSWORD = "newPassword";
	String OLDPASSWORD = "oldPassword";
	//	String TRUE = "True";
	//	String FALSE = "False";
	String TRUE = "Y";
	String FALSE = "N";

	String CHANGEPASSWORDREQUEST = "changePasswordRequest";
	String APPZILLON_ROOT_CREATE_USER_REQ = "appzillonCreateUserRequest";
	String APPZILLON_ROOT_CREATE_USER_RES = "appzillonCreateUserResponse";
	String APPZILLON_ROOT_REGISTER_USER_REQ = "appzillonUserRegistrationRequest";
	String APPZILLON_ROOT_REGISTER_USER_RES = "appzillonUserRegistrationResponse";
	String APPZILLON_USER_AUTHENTICATION_REQ = "appzillonUserAuthorizationRequest";
	String APPZILLON_USER_AUTHENTICATION_RES = "appzillonUserAuthorizationResponse";
	String REGISTER = "register";
	String APPZILLON_ROOT_ROLES = "roles";
	String APPZILLON_ROOT_CURRENT_PIN = "currentPin";
	String APPZILLON_ROOT_DEVICES = "Devices";
	String APPZILLON_ROOT_UPDATE = "update";
	String APPZILLON_ROOT_SEARCH_USR_ROLE_REQ = "appzillonSearchUserRoleRequest";
	String APPZILLON_ROOT_USR_ROLE_RES = "appzillonSearchUserRoleResponse";
	String APPZILLON_ROOT_DEL_USR_REQ = "appzillonDeleteUserRequest";
	String APPZILLON_ROOT_DEL_USR_RES = "appzillonDeleteUserResponse";
	String APPZILLON_ROOT_LNGEN = "en";
	String APPZILLON_ROOT_EMAILID = "emailid";
	String APPZILLON_ROOT_MAIL_TYPE = "MAIL";

	String APPZILLON_ROOT_LOGIN_REQUEST = "loginRequest";
	String APPZILLON_ROOT_USR_STATUS = "userStatus";
	String APPZILLON_ROOT_USER_EMAILID_REQ = "appzillonUserEmailIdReq";
	String APPZILLON_ROOT_GET_ROLE_BY_APP_USERID_RES = "appzillonGetRolesByAppIDUserIDResponse";
	String APPZILLON_ROOT_GET_ROLE_BY_APP_USERID_REQ = "appzillonGetRolesByAppIDUserIDRequest";
	String APPZILLON_ROOT_GET_ROLE_BY_APPID_REQ = "appzillonGetRolesByAppIDRequest";
	String APPZILLON_ROOT_GET_ROLE_BY_APPID_RES = "appzillonGetRolesByAppIDResponse";
	String APPZILLON_ROOT_PWD_RESET_REQ = "appzillonPasswordResetRequest";
	String APPZILLON_FORGOT_PWD_RESET_REQ = "appzillonForgotPasswordRequest";
	String APPZILLON_FORGOT_PWD_RESET_RES = "appzillonForgotPasswordResponse";
	String APPZILLON_ROOT_PWD_RESET_RES = "appzillonPasswordResetResponse";
	String APPZILLON_ROOT_UNLOCK_USR_REQ = "appzillonUnlockUserRequest";
	String APPZILLON_ROOT_UNLOCK_USR_RES = "appzillonUnlockUserResponse";
	String APPZILLON_ROOT_GET_ALL_USR_ROLE_RES = "appzillonGetAllUserRoleResponse";
	String APPZILLON_ROOT_CREATE_PWD_RULES_RES = "appzillonCreatePasswordRulesResponse";
	String APPZILLON_ROOT_DEL_PWD_RULES_REQ = "appzillonDeletePasswordRulesRequest";
	String APPZILLON_ROOT_GET_PWD_RULES_REQ = "appzillonGetPasswordRulesRequest";
	String APPZILLON_ROOT_CREATE_PWD_RULES_REQ = "appzillonCreatePasswordRulesRequest";
	String APPZILLON_ROOT_DEL_PWD_RULES_RES = "appzillonDeletePasswordRulesResponse";
	String APPZILLON_ROOT_GET_ALL_USR_DETAIL_RES = "appzillonGetAllUserDetailsResponse";
	String APPZILLON_ROOT_GET_PWD_RULES_RES = "appzillonGetPasswordRulesResponse";
	String APPZILLON_ROOT_GET_USR_REQ = "appzillonGetUserRequest";
	String APPZILLON_ROOT_UPDATE_USR_REQ = "appzillonUpdateUserRequest";
	String APPZILLON_ROOT_UPDATE_USR_RES = "appzillonUpdateUserResponse";
	String APPZILLON_ROOT_UPDATE_SECURITYRULES_REQ = "appzillonUpdatePasswordRulesRequest";
	String APPZILLON_ROOT_UPDATE_SECURITYRULES_RES = "appzillonUpdatePasswordRulesResponse";
	String APPZILLON_ROOT_PUSH_NOTIFICATIONS_REQ = "appzillonPushNotificationRequest";
	String APPZILLON_ROOT_PUSH_NOTIFICATION_RESP = "appzillonPushNotificationResponse";
	String APPZILLON_ROOT_SMS_AUDIT_LOG_HANDLER = "smsAuditLogHandler";
	String APPZILLON_ROOT_SMS_USER_PROFILE_HANDLER = "smsUserProfileHandler";
	String APPZILLON_ROOT_SMS_SCREEN_HANDLER = "smsScreenHandler";
	String APPZILLON_ROOT_SMS_REPORT_HANDLER = "smsReportHandler";
	String APPZILLON_ROOT_SMS_VAL_PWD_REQ = "validatePasswordRequest";
	String APPZILLON_ROOT_SMS_VAL_PWD_RES = "validatePasswordResponse";

	String APPZILLON_ROOT_LOGIN_RES = "loginResponse";
	String APPZILLON_ROOT_CANPROCEED = "canProceed";
	String APPZILLON_ROOT_INTERFACE_ID = "INTERFACE_ID";
	String APPZILLON_ROOT_DESCRIPTION = "DESCRIPTION";
	String APPZILLON_ROOT_APPID = "appid";

	// report constants start
	String REPORT_DATA = "reportData";
	String REPORT_DETAILS = "reportDetails";
	String REPORT_TYPE = "reportType";
	String REPORT_FILE_TYPE = "fileType";
	String REPORT_URL = "url";
	String REPORT_ENCODED = "encoded";
	String REPORT_JRXML_FILE_EXT = "_jasper.jrxml";
	String REPORT_JASPER_FILE_EXT = "_jasper.jasper";
	String REPORT_PDF_FILE_EXT = ".pdf";
	String REPORT_PDF_FILE = "pdf";
	String REPORT_XLSX = "xlsx";
	String REPORT_XLS = "xls";
	String REPORT_XLSX_EXT = ".xlsx";
	String REPORT_XLS_EXT = ".xls";
	String REPORT_HTML = "html";
	String REPORT_HTML_EXT = ".html";
	String REPORT_FILE = "file";
	String REPORT_FILENAME = "fileName";
	String ERROR = "error";
	String REPORT_DOWNLOAD_FILE_PATH = "downloadFilePath";
	String FILE_CONTENT = "fileContents";
	String PDFREPORT_CONSTANTS_FILE_NAME = "PDFReport";
	String REPORT_PARAMS = "params";
	String REPORT_JRXML_PATH = "REPORTJRXMLPATH";

	// report constants end
	String SERVICE_TYPE_VALIDATE_SESSION = "ValidateSession";
	String SERVICE_TYPE_CREATE_UPDATE_SESSION = "CreateUpdateSession";
	String SERVICE_TYPE_UPDATE_SESSION_IF_EXISTS = "UpdateLastReqTimeIfSessionExists";

	String NO_DESCRIPTION = "No description";
	String NO_RECORD_FOUND = "No record found";

	String BEAN_SMS_SESSION_MANAGER = "sesssionManagerBean";
	String BEAN_SMS_SESSION_HANDLER = "sesssionHandlerBean";
	String BEAN_SMS_AUTHENTICATION_HANDLER = "smsLoginLogoutRequestHandler";
	String BEAN_SMS_CHANGE_PASSWORD_HANDLER = "smsChangePasswordHandler";
	String BEAN_SMS_DECRYPT_HANDLER = "smsDecryptHandler";
	String BEAN_SMS_AUTHORIZATION_HANDLER = "smsAuthorizationHandler";
	String BEAN_SMS_ROLE_PROFILE_HANDLER = "smsRoleProfileHandler";
	String BEAN_SMS_USER_PROFILE_HANDLER = "smsUserProfileHandler";
	String APPZDBFETCHLOVREQUEST = "fetchLOVReq";
	String APPZJMSRESPUPDATEREQUEST = "JMSRespUpdateReq";
	String APPZJMSREQINSERTREQUEST = "JMSReqInsertReq";
	String APPZGETJMSSTATUS = "appzillonGetJMSStatus";
	String SERVICE_TYPE_LOGOUT = "AppzillonLogout";
	String SERVICE_TYPE_CLEAR_SESSION = "AppzillonClearSession";

	String MAIL_URL_SEPARATOR_DOUBLE_SLASH = "//";
	String MAIL_URL_SEPARATOR_COLON = ":";
	String MAIL_URL_CONSTANTS_USER_NAME = "&username=";
	String MAIL_URL_CONSTANTS_PASSWORD = "&password=";
	String MAIL_URL_CONSTANTS_TO = "?to=";
	String MAIL_URL_CONSTANTS_FROM = "&from=";
	String MAIL_URL_CONSTANTS_SUBJECT = "&subject=";
	String MAIL_URL_CONSTANTS_CC = "&cc=";
	String MAIL_URL_CONSTANTS_BCC = "&bcc=";
	String MAIL_CONSTANTS_CC = "CC";
	String MAIL_CONSTANTS_BCC = "BCC";
	String MAIL_CONSTANTS_FILE_NAME_PREFIX_CREATE_USER = "CreateUser_";
	String MAIL_CONSTANTS_FILE_NAME_PREFIX_REGISTER_USER = "RegisterUser_";
	String MAIL_CONSTANTS_FILE_NAME_PREFIX_CREATE_WITH_PWD_USER = "CreateUserWithPwd_";
	String MAIL_CONSTANTS_FILE_NAME_PREFIX_PASSWORD_RESET = "PasswordReset_";
	String MAIL_CONSTANTS_FILE_NAME_PREFIX_FORGOT_PASSWORD = "ForgotPassword_";
	String MAIL_CONSTANTS_FILE_NAME_PREFIX_CHANGE_PASSWORD = "ChangePassword_";
	String MAIL_CONSTANTS_SUBJECT = "subject";
	String MAIL_CONSTANTS_BODY = "body";
	String MAIL_CONSTANTS_PASSWORD = "password";
	String MAIL_FILLER_USERID = "$userid";
	String MAIL_FILLER_USER_NAME = "$username";
	String MAIL_FILLER_USER_PASSWORD = "$userpassword";
	String MAIL_FILLER_CREATED_DATE = "$createdtime";
	String MAIL_FILLER_CREATED_BY = "$createdby";
	String MAIL_FILLER_VALID_FOR = "$validfor";
	String MAIL_FILLER_APP_ID = "$appId";
	String MAIL_FILLER_APP_DESC = "$appDesc";
	String SMS_CONSTANTS_BODY = "smsMessage";
	String NOTIFICATION_CONSTANTS_BODY = "notificationMessage";

	String EXTERNAL_SERVICE_INTEFACE_TYPE_CACHE = "CACHE";
	String EXTERNAL_SERVICE_IMPL_BEAN_ID_CACHE = "camelCacheClient";

	String LDAP_TEMPLATE = "_ldapTemplate";
	String LDAP_CONSTANTS_OBJECTCLASS = "objectClass";
	String LDAP_CONSTANTS_SCOPE = "scope";
	String LDAP_SPRING_URI_PREFIX = "spring-ldap:";
	String LDAP_CONSTANTS_OPERATION = "operation";
	String LDAP_CONSTANTS_ADD = "add";
	String LDAP_CONSTANTS_UPDATE = "update";
	String LDAP_CONSTANTS_DELETE = "delete";
	String LDAP_CONSTANTS_SEARCH = "search";
	String LDAP_CONSTANTS_DN = "dn";
	String LDAP_CONSTANTS_ADD_ATTRIBUTES = "addAttributes";
	String LDAP_CONSTANTS_REPLACE_ATTRIBUTES = "replaceAttributes";
	String LDAP_CONSTANTS_DELETE_ATTRIBUTES = "deleteAttributes";
	String LDAP_CONSTANTS_FILTER = "filter";
	String LDAP_CONSTANTS_ATTRIBUTES = "attributes";
	String LDAP_CONSTANTS_OBJECT_CLASSES = "objectClasses";

	String HTTP_CALL_TYPE_POST = "POST";
	String HTTP_CALL_TYPE_GET = "GET";
	String HTTP_CALL_TYPE_PUT = "PUT";
	String HTTP_CALL_TYPE_DELETE = "DELETE";
	String HTTP_APPEND_TIMEOUT = "?httpClient.soTimeout=";
	String KEY_STORE_PATH = "KEYSTOREPATH";
	String KEY_STORE_PASSWORD = "KEYSTOREPWD";
	String TRUST_STORE_PATH = "TRUSTSTOREPATH";
	String TRUST_STORE_PASSWORD = "TRUSTSTOREPWD";
	String SYSTEM_PROPERTY_SSL_TRUST_STORE = "javax.net.ssl.trustStore";
	String SYSTEM_PROPERTY_SSL_TRUST_STORE_PASSWORD = "javax.net.ssl.trustStorePassword";
	String SYSTEM_PROPERTY_SSL_KEY_STORE = "javax.net.ssl.keyStore";
	String SYSTEM_PROPERTY_SSL_KEY_STORE_PASSWORD = "javax.net.ssl.keyStorePassword";
	String SSL_CONTEXT_PARAMETERS = "sslContextParameters=#sslContextParameters";

	String AMD = "&";
	String SOAP_VERSION_SOAP12 = "SOAP12";
	String SOAP_URL_MSG_FACTORY2_TIMEOUT = "messageFactory=#messageFactory12&timeout=";
	String SOAP_URL_MSG_FACTORY1_TIMEOUT = "messageFactory=#messageFactory11&timeout=";
	String SOAP_URL_SOAP_ACTION = "soapAction=";
	String EJB_SERIALIZABLE_OBJECT_TYPE = "serializableJavaObject";

	String JMS_REQ_PAYLOAD = "reqpayload";
	String JMS_REQ_TYPE = "reqType";
	String JMS_REQ_QUEUE = "reqQueue";
	String JMS_RESP_QUEUE = "respQueue";
	String JMS_RESP_TYPE = "respType";
	String JMS_RESP_MSG = "respMsg";
	String JMS_MSG_CORRELATION_ID = "msgCorrelationID";
	String JMS_DEFAULT_APPENDER = "?exchangePattern=InOnly&disableReplyTo=true";
	String JMS_APPEND_MSG_TYPE = "&jmsMessageType=";
	String JMS_MSG_TYPE_OBJECT = "Object";
	String JMS_MSG_TYPE_BYTES = "Bytes";
	String JMS_MSG_TYPE_STREAM = "Stream";
	String JMS_MSG_TYPE_MAP = "Map";
	String JMS_MSG_TYPE_TEXT = "Text";
	String JMS_CAMEL_QUEUE_RESOLVER = "camelJMSQueueResolver";
	String JMS_CAMEL_CONFIGURATION = "jmsConfiguration";
	String JMS_CAMEL_COMPONENT = "jmsComponent";
	String JMS_CAMEL_JNDI_RESOLVER = "jndiDestinationResolver";
	String JMS_APPEND_TIMEOUT = "requestTimeout=";
	String JMS_APPEND_AND_REPLY_Q = "&replyTo=";
	String JMS_APPEND_AND_USER = "&username=";
	String JMS_APPEND_AND_PASS = "&password=";
	String JMS_CONNECTIONFACTORY = "jms/RemoteConnectionFactory";
	String JMS_JAVA_NAMING_SEC_PRINCIPAL = "java.naming.security.principal";
	String JMS_JAVA_NAMING_SEC_CREDENTIALS = "java.naming.security.credentials";
	String JMS_MSG_ID = "msgId";
	int JMS_STATUS_SUCCESS = 1; // sent
	int JMS_STATUS_PENDING = 0; // success
	String XML = "XML";
	String FILE_SIZE_EXCEED = "File too Large";
	String AUTHREQUEST = "authRequest";
	String AUTHRESPONSE = "authResponse";
	String _000NEW = "000NEW";
	String _000LOGIN = "000LOGIN";
	String AUTHORIZATION_STATUS = "authStatus";
	// String OTP_REQUIRED = "otpRequired";

	String LOGGER_FRAMEWORKS = "com.iexceed.appzillon.rest"; //"com.iexceed.appzillon.frameworks";
	String LOGGER_SMS = "com.iexceed.appzillon.rest"; //"com.iexceed.appzillon.sms";
	String LOGGER_NOTIFICATION = "com.iexceed.appzillon.rest"; //"com.iexceed.appzillon.notification";
	String LOGGER_RESTFULL_SERVICES = "com.iexceed.appzillon.rest";
	String LOGGER_DOMAIN = "com.iexceed.appzillon.rest"; //"com.iexceed.appzillon.domain";
	String LOGGER_WORKFLOW = "com.iexceed.appzillon.rest";

	String LOGGER_PREFIX_FRAMEWORKS = "[FrameworkServices] =>";
	String LOGGER_PREFIX_DOMAIN = "[Domain] => ";
	String LOGGER_PREFIX_SMS = "[SMS] => ";
	String LOGGER_PREFIX_NOTIFICAITON = "[Notifications] => ";
	String LOGGER_PREFIX_SERVICES_ROUTER = "[RequestDispatcher] => ";
	String LOGGER_PREFIX_RESTFULL = "[RESTFull Services] => ";
	String LOGGER_PREFIX_WORKFLOW = "[WORKFLOW] => ";

	String SERVICES_BEAN_EJB = "EJBService";
	String SERVICES_BEAN_HTTP = "HTTPService";
	String SERVICES_BEAN_ISO = "ISO8583Service";
	String SERVICES_BEAN_JMS = "JMSService";
	int SERVICES_DEFAULT_TIMEOUT_TIME = 120;
	String ISO8583_RESPONSE_NODE = "Response";
	String ISO8583_REQUEST_NODE = "Request";
	String ISO_SIGN_ON = "signOn";
	String ALL = "all";

	String DELETE_DEVICE_REQUEST = "appzillonDeleteDeviceRequest";
	String DELETE_DEVICE_RESPONSE = "appzillonDeleteDeviceResponse";
	String CREATE_DEVICE_REQUEST = "appzillonCreateDeviceRequest";
	String CREATE_DEVICE_RESPONSE = "appzillonCreateDeviceResponse";
	String UPDATE_DEVICE_REQUEST = "appzillonUpdateDeviceRequest";
	String UPDATE_DEVICE_RESPONSE = "appzillonUpdateDeviceResponse";
	String SEARCH_DEVICE_REQUEST = "appzillonSearchDeviceRequest";
	String SEARCH_DEVICE_RESPONSE = "appzillonSearchDeviceResponse";

	String DELETE_GROUP_REQUEST = "appzillonDeleteGroupRequest";
	String DELETE_GROUP_RESPONSE = "appzillonDeleteGroupResponse";
	String CREATE_GROUP_REQUEST = "appzillonCreateGroupRequest";
	String CREATE_GROUP_RESPONSE = "appzillonCreateGroupResponse";
	String UPDATE_GROUP_REQUEST = "appzillonUpdateGroupRequest";
	String UPDATE_GROUP_RESPONSE = "appzillonUpdateGroupResponse";
	String SEARCH_GROUP_REQUEST = "appzillonSearchGroupRequest";
	String SEARCH_GROUP_RESPONSE = "appzillonSearchGroupResponse";
	String GET_GROUP_DETAIL_REQUEST = "appzillonGetGroupDetailRequest";
	String GET_GROUP_DETAIL_RESPONSE = "appzillonGetGroupDetailResponse";
	String NOTIFICATION_APP_DETAIL_RESPONSE = "appzillonNotificationAppDetailResponse";
	String NOTIFICATION_APP_DETAIL_REQUEST = "appzillonNotificationAppDetailRequest";
	String MEMBER = "member";
	String NONMEMBER = "nonMember";
	String DEVICE_ID_MULTIPLE = "deviceIds";
	// String PUSH_NOTIFICATIONS_REQUEST =
	// "appzillonPushNotificationRequest";
	String APPZILLON_ROOT_NF_TXNARRAY = "TransactionArray";
	String MAIL_CONSTANTS_EMAIL_ID = "emailid";
	String BEAN_APPEND_SERVICE = "_service";
	String BEAN_APPEND_SERVICE_PROC = "_proc";

	String GET_USER_ROLES = "getUserRoles";
	String EXISTS = "exists";
	String ROLESCREENAPP = "rolerrscreenapp";
	String ROLEINTERFACEAPP = "roleintfappid";
	String MESSAGE = "message";
	String CHANGEPASSWORDRESPONSE = "changePasswordResponse";
	String VALID_PASSWORD = "validPassword";
	String CREATE_ROLEMASTER_REQUEST = "appzillonCreateRoleMasterRequest";
	String CREATE_ROLEMASTER_RESPONSE = "appzillonCreateRoleMasterResponse";
	String UPDATE_ROLEMASTER_REQUEST = "appzillonUpdateRoleMasterRequest";
	String UPDATE_ROLEMASTER_RESPONSE = "appzillonUpdateRoleMasterResponse";
	String DELETE_ROLEMASTER_REQUEST = "appzillonDeleteRoleMasterRequest";
	String DELETE_ROLEMASTER_RESPONSE = "appzillonDeleteRoleMasterResponse";
	String GET_ROLEMASTER_RESPONSE = "appzillonGetRoleMasterResponse";
	String GET_ROLEMASTER_REQUEST = "appzillonGetRoleMasterRequest";
	String INTERFACES = "interfaces";
	String SCREENS = "screens";
	String USER_PRIVS = "privs";
	String USER_PRIVS_SCREENS = "scrs";
	String USER_PRIVS_INTERFACES = "ifaces";
	String USER_PRIVS_INTERFACES_ACCESSTYPE = "ifacesAccessType";
	String USER_PRIVS_SCREENS_ACCESSSTYPE = "scrsAccessType";
	String USER_PRIVS_CONTROLS_ACCESSTYPE = "controlsAccessType";
	String USER_PRIVS_ACCESS_ALLOWED = "A";
	String USER_PRIVS_ACCESS_DENIED = "D";
	String USER_PRIVS_NOT_REQUIRED = "N";
	String CONTROLS = "controls";
	String PERCENT = "%";
	String SERVICES_BEAN_LOV = "LOVService";
	String SERVICES_BEAN_LOV_IMPL = "LOVServiceImpl";
	String DEVICE_GROUP_DESCRIPTION = "groupDesc";
	String SCREEN_IDS = "screenIds";
	String INTERFACE_IDS = "interfaceIds";
	String AUTH_USER_ID = "UserId";
	String AUTH_APP_ID = "AppId";
	String AUTH_LAST_LOGIN = "LastLogin";
	String START_DATE = "startDate";
	String END_DATE = "endDate";
	String START_TIME = "startTime";
	String END_TIME = "endTime";
	String EXT_START_TIME = "extStartTime";
	String EXT_END_TIME = "extEndTime";
	String TRANSACTION_ID = "transactionId";
	// String SPECIAL_CHARS = "`~!@#$%^&*()[]{}|:;',.<>?";
	String SPECIAL_CHARS = "~!@#$%^&*()[]{}|:',.<>?";

	String HEADER = "header";
	String META_INF_SPRING = "META-INF/spring/";
	String ISO_CONFIG_XML = "_ISOConfig.xml";
	String METHOD_TYPE = "methodType";
	String CONNECTED = "connected";
	String JNDI_TEMPLATE = "_jndiTemplate";
	String OWASP_SANTIZER_REQ = "OWASPSANITIZERREQUIRED";
	String MAIL_ATTACHED_FILES = "attachments";
	String FILE_NAME = "name";
	String CONTENT = "content";

	String WORKFLOWID = "workflowId";
	String STAGEID = "stageId";
	String NEXTSTAGEID = "nextStageId";
	String SCREENDATA = "screenData";
	String SEQNO = "seqNo";
	String CURRENTSTAGE = "currentStage";
	String WFTXNREF = "wfTxnRef";
	String CURRSTAGEID = "currStageId";
	String ACTION = "action";
	String SERVICE_WORKFLOW = "WorkflowService";
	String WORKFLOW_PERSIST_REQUEST = "appzillonWorkflowPersistRequest";
	String WORKFLOW_QUERY_DB_REQUEST = "appzillonWorkflowQueryDbRequest";
	String WORKFLOW_QUERY_REQUEST = "appzillonWorkflowQueryRequest";
	String WORKFLOW_DASHBOARD_QUERY_REQUEST = "appzillonWorkflowDashboardQueryRequest";
	String WORKFLOW_PERSIST_RESPONSE = "appzillonWorkflowPersistResponse";
	String WORKFLOW_QUERY_DB_RESPONSE = "appzillonWorkflowQueryDbResponse";
	String WORKFLOW_QUERY_RESPONSE = "appzillonWorkflowQueryResponse";
	String WORKFLOW_DASHBOARD_QUERY_RESPONSE = "appzillonWorkflowDashboardQueryResponse";
	String UPLOADFILEREQUEST = "appzillonUploadFileRequest";
	String UPLOADFILERESPONSE = "appzillonUploadFileResponse";
	String UPLOAD_REQ = "appzillonRequest";
	String NULL = "null";
	String SEARCHFILEREQUEST = "appzillonSearchFileRequest";
	String SEARCHFILERESPONSE = "appzillonSearchFileResponse";
	String DELETEFILEREQUEST = "appzillonDeleteFileRequest";
	String DELETEFILERESPONSE = "appzillonDeleteFileResponse";
	String FILEPUSHSERVICEREQUEST = "appzillonFilePushServiceRequest";
	String FILEPUSHSERVICERESPONSE = "appzillonFilePushServiceResponse";
	String FILEPUSHSERVICEWSREQUEST = "appzillonFilePushServiceWSRequest";
	String FILEPUSHSERVICEWSRESPONSE = "appzillonFilePushServiceWSResponse";
	String BASE64STATUS = "base64";
	String FILE_SERVICE = "appzillonFileService";
	String FRM_NOT_SUPPORTED_YET = "Not supported yet.";
	String JSON_EXCEPTION = " JsonException :";
	String IOEXCEPTION = "IOException";
	String ILLEGAL_ACCESS_EXCEPTION = "IllegalAccessException";
	String ILLEGAL_ARGUMENT_EXCEPTION = "IllegalArgumentException";
	String INVOCATION_TARGET_EXCEPTION = "InvocationTargetException";
	String EXCEPTION = "Exception";
	String DEFAULT_TIMEOUT = "SERVICETIMEOUT";

	// String AUTO_PASSWORD_GENERATE = "autoPasswordGenerate";
	String ALLOW_USER_PASSWORD_ENTRY = "allowUserPasswordEntry";
	String PASSWORD_ON_AUTHORIZATION = "passwordOnAuthorization";
	String PASSWORD_COMM_CHANNEL = "passwordCommunicationChannel";
	String AUTO_APPROVE = "autoApprove";
	// String PASSWORD_EXPIRY = "passwordExpiry";
	String APPZILLON_ROOT_SMS_LOGGING_HANDLER = "smsLoggingHandler";
	String SERVICE_ERROR_LOGGING = "errorLogging";
	String INTERFACE_ID_ERROR_LOGGING = "appzillonErrorLogging";
	String DEVICE_LOGGING_SERVICE = "deviceLoggingService";

	String INTERFACE_MULTIFACTOR_DEVICE_REGISTRATION = "appzillonDeviceRegistration";
	String SERVICE_DEVICE_MASTER = "ServiceDeviceMaster";
	String SERVICE_CHECK_DEVICE_MOBILE = "ServiceCheckDeviceMobile";
	String INTERFACE_ID_DEVICE_STATUS_REQ = "deviceStatus_Req";
	String DEVICE_STATUS_REQUEST = "deviceStatusRequest";
	String DEVICE_STATUS_RESPONSE = "deviceStatusResponse";
	String DEVICE_REGISTER_REQUEST = "deviceRegisterRequest";
	String DEVICE_REGISTER_RESPONSE = "deviceRegisterResponse";
	// Added for User Device Registration
	String USER_DEVICE_REGISTER_REQUEST = "userDeviceRegisterRequest";
	String USER_DEVICE_REGISTER_RESPONSE = "userDeviceRegisterResponse";
	String INTERFACE_ID_USER_DEVICE_REGISTRATION = "appzillonUserDeviceRegistration";
	String USER_DEVICE_REGISTERED_SUCCESSFULLY = "User Device Registered Successfully";
	String ADMIN_APPROVAL_REQUIRED = "Admin Approval Required";

	String SERVICE_OTA = "serviceOTA";
	String INTERFACE_ID_OTA_GET_CHILD_APP_DETAILS = "appzillonGetChildAppDetails";
	String INTERFACE_ID_OTA_GET_APP_MASTER_DETAILS = "appzillonGetAppMasterDetails";
	String INTERFACE_ID_OTA_CREATE_APP_MASTER = "appzillonCreateAppMaster";
	String INTERFACE_ID_OTA_UPDATE_APP_MASTER = "appzillonUpdateAppMaster";
	String INTERFACE_ID_OTA_SEARCH_APP_MASTER = "appzillonSearchAppMaster";
	String INTERFACE_ID_OTA_DELETE_APP_MASTER = "appzillonDeleteAppMaster";

	String INTERFACE_ID_OTA_GET_APP_FILE = "appzillonGetAppFile";
	String INTERFACE_ID_OTA_CREATE_APP_FILE = "appzillonCreateAppFile";
	String INTERFACE_ID_OTA_UPDATE_APP_FILE = "appzillonUpdateAppFile";
	String INTERFACE_ID_OTA_SEARCH_APP_FILE = "appzillonSearchAppFile";
	String INTERFACE_ID_OTA_DELETE_APP_FILE = "appzillonDeleteAppFile";

	String OTAFILEDOWNLOAD_REQUEST = "appzillonOTAFileDownloadRequest";
	String OTAFILEDOWNLOAD_RESPONSE = "appzillonOTAFileDownloadResponse";
	String INTERFACE_ID_OTAFILE_DOWNLOADREQ = "appzillonOTAFileDownloadReq";
	String APPVERSION = "appVersion";
	String IDE_VERSION = "ideVersion";
	String PRELOGIN = "preLogin";
	String CONTAINER_APP = "containerApp";
	String OTA_REQUIRED = "otaReq";
	String REMOTE_DEBUG = "remoteDebug";
	String EXPIRY_DATE = "expiryDate";
	String PARENT_APPID = "parentAppId";
	String APP_NAME = "appName";
	String FILE_PATH = "filepath";
	String FILEPATH = "filePath";
	String MAX_UPLOAD_FILE_SIZE = "MAXUPLOADFILESIZE";
	String OS = "os";
	String CHILD_APP_ID = "childAppId";
	/* Appzillon 3.1 -66 -- By ripu- for Device Master */
	String INTERFACE_ID_SEARCH_DEVICE_MASTER = "appzillonSearchDeviceMaster";
	String INTERFACE_ID_DELETE_DEVICE_MASTER = "appzillonDeleteDeviceMaster";
	String INTERFACE_ID_UPDATE_DEVICE_MASTER = "appzillonUpdateDeviceMaster";
	String APPZILLON_ROOT_SMS_OTA_HANDLER = "smsOTAHandler";
	String APPZILLON_ROOT_SMS_DEVICE_MASTER_HANDLER = "smsDeviceMaster";
	/* Appzillon 3.1 -66 END */

	/** Appzillon 3.1 - 69 -- Start */
	String BEAN_EXTENDED_USER_CREATION = "customUserCreation";
	/* Appzillon 3.1 - 69 -- END */

	/* Appzillon 3.1 - 60-- By ripu- for Device Master */
	// String MOBILE_NUMBER = "mobileNum";
	String HASH_DEVICE_ID = "#DeviceId";
	String PLAIN_TEXT = "PlainText";
	String AUTHENTICATION_TYPE = "AUTHENTICATIONTYPE";
	/* Appzillon 3.1 - 60 end */

	/* Appzillon 3.1 -65 -- By ripu- for Device Master */
	String MOBILE_1 = "mobile1";
	String MOBILE_2 = "mobile2";
	String MODEL = "model";
	String MAKE = "make";
	String SCREEN_RESOLUTION = "screenResolution";
	String WIPE_OUT = "wipeout";
	/* Appzillon 3.1 - 65 end */

	/* Appzillon 3.1 -68 Start */
	String SERVICE_TASK_REPAIR = "taskRepairService";
	String INTERFACE_ID_TASK_REPAIR_SEARCH = "searchTaskRepair";
	String INTERFACE_ID_TASK_REPAIR_UPDATE = "updateTaskRepair";
	/* Appzillon 3.1 -68 End */

	/* Appzillon 3.1 -14 Start */
	String APPZILLON_ERROR_LOGGING_REQUEST = "appzillonErrorLoggingRequest";
	String APPZILLON_ERROR_LOGGING_RESPONSE = "appzillonErrorLoggingResponse";
	String RESPONSE = "response";
	String LOGGER_ERROR = "com.iexceed.appzillon.errorLogging";
	String EXPIRED = "expired";
	String APPZILLON_APP_MASTER_REQUEST = "appzillonAppMasterRequest";
	/* Appzillon 3.1 -14 End */

	String SERVER_PROP_FILE_CONSTANT = "commons";
	String SERVER_SECURITY_ENCRYPTION_KEY = "ENCRYPTIONKEY";
	String SERVER_SECURITY_ENCRYPTION_REQ_NO = "N";
	String SERVER_SECURITY_ENCRYPTION_REQ_YES = "Y";
	/* Appzillon 3.1 -14 End */
	/* Appzillon 3.1 USSD related constants **/
	String META_INF_USSD = "META-INF/USSD/";
	String USSD_ID = "ID";
	String MESSAGETEXT = "MESSAGETEXT";
	String MESSAGES = "MESSAGES";
	String MESSAGENODE = "MESSAGE";
	String NEXTACTION = "NEXTACTION";
	String NEXTSTEP = "NEXTSTEP";
	String CONDITION = "CONDITION";
	String TAG = "TAG";
	String STEP = "STEP";
	String USSD = "USSD";
	String USSDREQUEST = "REQUEST";
	String USSDRESPONSE = "RESPONSE";
	String USSD_INTERFACE = "INTERFACE";
	String CALLSERVER = "CALLSERVER";
	String ACTIONS = "actions";
	String LASTCONDITION = "lastcondition";
	String PERSISTENCE = "PERSISTENCE";
	String DEFAULTLANGUAGE = "defaultLanguage";
	String LANGUAGE = "LANGUAGE";
	String CODE = "CODE";
	String FLAG = "flag";
	String INTERFACENAME = "INTERFACENAME";

	String SERVICE_USSD = "USSDService";
	String INTERFACE_TYPE_USSD = "USSD";
	String INTERFACE_ID_USSD_STARTUP = "appzillonUSSDStartup";
	String INTERFACE_ID_USSD_LOGINMENU = "appzillonUSSDLoginMenu";
	String INTERFACE_ID_USSD_LOGINPROMPT = "appzillonUSSDLoginPrompt";
	String INTERFACE_ID_USSD_ROOTMENU = "appzillonUSSDRootMenu";
	String INTERFACE_ID_USSD_ERROR = "appzillonUSSDError";
	String INTERFACE_ID_USSD_INITIATEFUNDTRANSFER = "initiateFundTransfer";
	String INTERFACE_ID_USSD_TRANSFERCONFIRM = "appzillonTransferAmountConfirm";
	String USSD_FILEROOTPATH = "fileRootPath";
	String USSD_INPUT = "Input";
	String USSD_DATA = "Data";
	String USSD_LANGCODE = "langCode";
	String USSD_MENUID = "MenuId";
	String USSD_ERRORCODE = "errorCode";
	String USSD_ROOT = "root";
	String USSD_REQUESTFILLERS = "REQUESTFILLERS";
	String USSD_FILLERMAP = "fillerMap";
	String USSD_CHILDS = "childs";
	String USSD_CHILD = "child";
	String USSD_REQUESTHEADER = "REQUESTHEADER";
	String USSD_REQUESTBODY = "REQUESTBODY";
	String USSD_TYPE = "type";
	String USSD_COMPLEX = "Complex";
	String USSD_ORDER = "order";
	String USSD_STATIC = "Static";
	String USSD_INTERNAL = "Internal";
	String USSD_SOAP = "Soap";
	String USSD_RESPONSEBODY = "RESPONSEBODY";
	String USSD_RESPONSEPARAMS = "RESPONSEPARAMS";
	String USSD_HYPERLINK = "hyperlink";
	String USSD_SERVICETYPE = "SERVICETYPE";
	String USSD_NEXTINTERFACEID = "nextInterfaceId";
	String USSD_NODE = "node";
	String USSD_RESPONSENODE = "responsenode";
	String USSD_FORMACTION = "formaction";
	String USSD_TITLE = "title";
	String EXCEPTION_PREFIX = "APZ";
	String USSD_STATICKEY = "statickey";
	String USSD_RESPONSEXML = "responseXml";
	String USSD_DISPLAYNODE = "displayNode";
	String USSD_PARAM = "param";
	String USSD_REQUESTPRECOMPUTES = "REQUESTPRECOMPUTES";
	String USSD_PRECOMPUTEMAP = "precomputeMap";
	String USSD_PRECOMPUTE = "preCompute";
	/*
	 * SMS Support related constants
	 */

	String VALUES = "VALUES";
	String VALUE = "VALUE";
	String KEY = "KEY";
	String DESCRIPTIONNODE = "DESCRIPTION";
	String SEPARATOR_SPACE = " ";
	String REQUEST_TYPE_BAL = "BAL";
	String REQUEST_TYPE_ACCOUNT_SUMMARY = "ACC";
	String REQUEST_TYPE_MINI_STATEMENT = "MINISTMT";
	String REQUEST_TYPE_FUNDS_TRANSFER_WITH_IN = "WITHIN";
	String REQUEST_TYPE_FUNDS_TRANSFER_WITH_IN_BANK = "INTRA";
	String REQUEST_TYPE_FUNDS_TRANSFER_INTER_BANK = "INTER";
	String REQUEST_TYPE_CHEQUE_BOOK_REQUEST = "CHQBR";
	String SMS_TEMP_CONST_ACC_NO = "$accountno";
	String SMS_TEMP_CURRENT_DATE = "$currentdate";
	String SMS_TEMP_CURRENCY_TYPE = "$currencytype";
	String SMS_TEMP_ACCOUNT_BALANCE = "$balanceamount";
	String SMS_TEMP_DEBIT_OR_CREDIT = "$debitorcredit";
	String SMS_TEMP_AMOUNT = "$amount";
	String NODE = "NODE";
	String ELEMENTS = "ELEMENTS";
	String ELEMENT = "ELEMENT";
	String NODENAME = "NODENAME";
	String ELEMENTNAME = "ELEMENTNAME";
	String TEMPLATE = "TEMPLATE";
	String ROOTNODE = "ROOTNODE";
	String RESPONSENODE = "RESPONSENODE";
	String RESPONSEDISPLAYELEMENTS = "RESPONSEDISPLAYELEMENTS";
	String INTERFACEID = "INTERFACEID";
	String MOBILENUMBER = "mobileNumber";
	String SMS_MESSAGE = "MESSAGE";
	String APPEND = "APPEND";
	String CONDITIONVALUE = "CONDITIONVALUE";
	String CONDITIONTAG = "CONDITIONTAG";
	String CONDITIONTYPE = "CONDITIONTYPE";
	String CONDITIONID = "CONDITIONID";
	String EQ = "EQ";
	String NEQ = "NEQ";
	String NAME_CAPS = "NAME";
	String ELEMENTVALUE = "ELEMENTVALUE";
	String SMS = "SMS";
	String APPZILLON = "APPZILLON";
	String FROM = "FROM";
	String META_INF_SMS = "META-INF/SMS/";
	String NOTIFICATION_WINDOWS_81_SID = "WIN81NOTIFREGID";
	String NOTIFICATION_WINDOWS_81_SECRET_KEY = "WIN81NOTIFKEY";
	/* */
	String SMS_COMM_PORT = "SMSCOMMPORT";
	String SMS_DEVICE_DESTINATION_PORT = "DEVICEDESTPORT";
	String CHECKDEFAULTAUTH = "checkDefaultAuth";

	String SERVICE_DRAG_DROP = "dragDropService";
	String LAYOUT = "layout";
	String PARENT_ID = "parentId";
	String ORDERS = "orders";
	String BLACKBERRY = "BLACKBERRY";
	String APPZILLON_SERVER_URL = "SERVERURL";
	String OTA_SOURCE_LOCATION = "OTASOURCELOCATION";
	String MESSAGE_SEPERATOR = "MSGSEPERATOR";
	String MAX_TRANSACTION_LOG_LENGTH = "MAXDBCOLLENGTH";
	String OS_BLACKBERRY_10 = "BLACKBERRY10";
	String SOURCE = "source";
	String INTERFACE_ID_NOTIFY_MOBILE_NUMBER = "appzillonNotifyMobileNumber";
	String INTERFACE_ID_NOTIFY_DEVICE = "appzillonNotifyDevice";

	String INTERFACE_ID_VALIDATE_OTP = "appzillonValidateOTP";

	String USER_PROFILE_PIC = "profilePic";
	String IMAGE_FOLDER = "AppzillonImages";
	String PROFILE_PIC = "profilePic";
	String FILE_UPLOAD_LOCATION = "FILEUPLOADLOCATION";
	String TXT = ".txt";

	String SERVICE_BEACON = "beaconService";
	String INTERFACE_ID_INSERT_BEACON = "appzillonInsertBeacon";
	String INTERFACE_ID_FETCH_BEACONDETAILS = "appzillonFetchBeaconDetails";
	String INTERFACE_ID_UPDATE_BEACONDETAILS = "appzillonUpdateBeaconDetails";
	String APPZILLON_ROOT_BEACON_INSERT_REQ = "appzillonBeaconInsertRequest";
	String APPZILLON_ROOT_BEACON_INSERT_RES = "appzillonBeaconInsertResponse";
	String APPZILLON_ROOT_BEACON_UPDATE_REQ = "appzillonBeaconUpdateRequest";
	String APPZILLON_ROOT_BEACON_UPDATE_RES = "appzillonBeaconUpdateResponse";
	String APPZILLON_ROOT_BEACON_FETCH_REQ = "appzillonBeaconFetchRequest";
	String APPZILLON_ROOT_BEACON_FETCH_RES = "appzillonBeaconFetchResponse";
	String PENDING = "P";
	String COMPLETED = "C";
	String WORK_IN_PROGRESS = "W";
	String BEACON_ID_REF = "id";
	String BEACON_USER_EMAILID = "emailId";

	String ISO8583_REQUEST_TYPE_BINARY = "binary";
	String ISO8583_REQUEST_HEADER_MESSAGE_LENGTH = "$MESSAGELENGTH";
	String RELATIVE_PATH = "relativePath";
	String OTP_REQUIRED_PROP = "OTPREQUIRED";
	String OTP_CHANNEL = "OTPCHANNEL";
	String OTP_EXPIRED = "E";
	String OTP_REQUIRED_ELEMENT = "OTPRequired";
	String INTERFACE_ID_REGENERATE_OTP = "appzillonReGenerateOtp";
	String OVERRIDEFLAG = "overrideFlag";
	String OVERRIDE = "overWrite";
	String INTERFACE_ID_SEND_SMS = "appzillonSendSMS";
	// For Device Master

	String REQUEST_ID = "requestId";
	String MESSAGE_HEADER_OTP_VALIDATE_STATUS = "otpValStatus";

	String SERVICE_OTP_VAL = "OTPEngineService";
	String SERVICE_OTP_UPDATE = "ServiceOtpUpdateValStatus";
	String SERVICE_OTP_DELETE = "ServiceOtpDelete";
	String SERVICE_VALIDATE_OTP = "ServiceValidateOtp";
	String SERVICE_OTP_LENGTH = "OTPLENGTH";
	String SERVICE_FETCH_OTP = "ServiceOtpDetails";
	String SERVICE_PROCESS_IFACE = "ServiceIFaceDetails";
	String SERVICE_UPDATE_PAYLOAD_STATUS = "ServiceOtpUpdatePayLoadStatus";
	String SERVICES_BEAN_VALIDATE_N_PROCESS_IMPL = "OTPValidateNProcessImpl";
	String INTERFACE_TYPE_OTP = "OTP";
	String SERVICE_TYPE_INVALIDATE_OTP = "AppzillonInvalidateOTP";
	//added to process resend request.
	String SERVICE_TYPE_OTP_RESEND="otpResend";
	//added for otpexpiry flag status ON 30/11/16
	String RESEND_EXPIRY = "RE";
	String VALIDATION_EXPIRY = "VE";
	String OTP_EXPIRY = "E";
	String OTP_PROCESSED = "P";
	String OTP_SERIAL_NO = "serialNo";
	String RE_GENERATE_OTP_REQ = "reGenerateOTPRequest";
	String SERVICE_TYPE_REGENARATE_OTP = "AppzillonRegenarateOTP";
	String SERVICE_TYPE_FETCH_SEQUENCE_VALUE = "AppzillonFetchSequenceValue";
	String SERVICE_SEQUENCE = "ServiceSequence";
	String SERVICE_AUGUMENTED_REALITY = "ServiceAugumentedReality";
	String SERVICE_TYPE_FETCH_AUGUMENTED_REALITY = "AppzillonFetchAugumentedReality";
	String INTERFACE_ID_FETCH_AUGUMENTED_REALITY = "appzillonFetchARDetails";

	//InfluxDB details
	String INFLUXDB_URL="influxDBUrl";
	String INFLUXDB_USERNAME="influxDBUsername";
	String INFLUXDB_PASSWORD="influxDBPassword";
	String INFLUXDB_DB_NAME="influxDBName";
	//Azure details
	String READ_PEM_FROM_VAULT ="READ_PEM_FROM_VAULT";
	String VAULT_NAME="VAULT_NAME";
	String CLIENT_ID ="CLIENT_ID";
	String CLIENT_SECRET ="CLIENT_SECRET";
	String VAULT_URL ="VAULT_URL";
	String APP_CONFIG_URL ="APP_CONFIG_URL";
	String TENANT_ID ="TENANT_ID";
	String AUTH_URL_APP_CONFIG ="AUTH_URL_APP_CONFIG";
	String AUTH_URL_KEY_VAULT ="AUTH_URL_KEY_VAULT";
	String CONTENT_TYPE_VALUE="application/json";
	String AZURE_VALUE = "value";
	String AZURE_KEY_VAULT ="KeyVault";
	String AZURE_APP_CONFIG="AppConfig";
	String AZURE_APP_CONFIG_KEY="Key";
	String CLOUD_LOGGING ="CLOUD_LOGGING";
	String INSTRUMENTATION_KEY = "INSTRUMENTATION_KEY";
	String CLOUD_AZURE = "Azure";
	String AZURE_CLIENT_ID ="client_id";
	String AZURE_CLIENT_SECRET = "client_secret";
	String AZURE_SCOPE="scope";
	String AZURE_SCOPE_URL ="https://vault.azure.net/.default";
	String AZURE_GRANT_TYPE = "grant_type";
	String AZURE_GRANT_TYPE_CLIENT_CREDENTIALS = "client_credentials";
	String ACCESS_TOKEN="access_token";
	String HTTP_PROTOCOL_TLS = "TLSv1.2";
	String HTTP_HEADER_ACCEPT="Accept";
	String AZURE_RESOURCE ="resource";
	String AZURE_RESOURCE_URL ="https://management.azure.com/";
	String URI="uri";
	String CLOUD_PROVIDER="CLOUD_PROVIDER";
	String KEY_VAULT_API_VERSION="?api-version=2016-10-01";
	String APP_CONFIG_API_VERSION ="?api-version=1.0";
	String PERSISTANCE_UNIT ="PERSISTENCE_UNIT";

	//Encryption length changes
	String APPZILLON_SAFE_BIT = "appzillonSafeBit";
	String PBS_PADDING = "AES/CBC/PKCS5padding";
	//String AUTHORIZATION="Authorization";
	// Scheduler constants

	String SERVICE_SCHEDULER = "SchedulerService";
	String INTERFACE_ID_SCHEDULER = "appzillonScheduler";
	String INTERFACE_TYPE_SCHEDULER = "SCHEDULER";
	String GROUP_NAME = "AppzillonCronGroups";
	String LOGGER_PREFIX_SCHEDULTER = "[Schedulers] =>";
	String DATA_JSON = "dataJson";
	String JOB_KEY = "key";
	String JOB_VALUE = "value";
	String STATUS = "status";
	String SCHEDULER_START = "start";
	String SCHEDULER_NOT_STARTED = "notStarted";
	String DELETE_JOB = "deleteJob";
	String START_JOB = "startJob";
	String NO_JOBS = "noJobsFound";
	String FIND_JOBS = "TbAsmiQuartzJob.findAll";
	String FIND_JOB = "TbAsmiQuartzJob.findAJob";
	String FIND_EXP_DETAILS = "TbAsmiQuartzExpression.findJobExpDetails";
	String JOB_NAME = "jobName";
	String JOB_STATUS = "jobStatus";
	String JOB_WORKING = "W";
	String JOB_COMPLETED = "C";
	String JOB_DELETED = "D";
	String SCHEDULER = "scheduler";
	String APPZILLON_ROOT_SCHEDULER_UPDATE_JOBSTATUS_REQ = "updateJobStatusRequest";
	String UPDATE_JOB_SERVICE = "updateJobService";
	String JOB = "job";
	String JOBS = "jobs";
	String PERSISTENT_UNIT = "appzillon-domain";
	String TRIGGER = "trigger";
	String SIMPLE_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss"; // "yyyy-MM-dd HH:mm:ss.S"
	String SIMPLE_DATE_TIME_FORMAT = "dd/MM/yyyy HH:mm:ss.SSS";

	String LOGGER_SCHEDULER = "com.iexceed.appzillon.scheduler";
	String UNAUTHORIZED = "U";
	String AUTHORIZED = "A";
	String ADDITIONAL_INFO1 = "addInfo1";
	String ADDITIONAL_INFO2 = "addInfo2";
	String ADDITIONAL_INFO3 = "addInfo3";
	String ADDITIONAL_INFO4 = "addInfo4";
	String ADDITIONAL_INFO5 = "addInfo5";
	String MESSAGE_HEADER_ORIGINATION = "origination";
	String PATH_PARAMETERS_LEFT_FILLER = "{";
	String PATH_PARAMETERS_RIGHT_FILLER = "}";
	String PATH_PARAMETERS_LEFT_FILLER_ENCODED = "%7B";
	String PATH_PARAMETERS_RIGHT_FILLER_ENCODED = "%7D";
	String CHARACTER_ENCODING_UTF_8 = "UTF-8";
	String INTERFACE_ID_SMS_TXN = "appzillonSmsLogTxn";
	String INTERFACE_ID_USSD_TXN = "appzillonUssdLogTxn";
	String INTERFACE_ID_TXT_MSLG_LOG = "appzillonTxtMslgLog";
	String AUTHORIZATION_REQUEST = "authorizationRequest";
	String AUTHORIZATION_RESPONSE = "authorizationResponse";
	String ONE_STRING_FORMAT = "1";
	String ZERO_STRING_FORMAT = "0";


	String TRANSACTION_APPZILLON_ADMIN = "appzillonadmin";
	String TRANSACTION_APPZILLON_APP_META = "appzillonappmeta";
	String INTERFACE_ID_SMS_USER = "appzillonSmsUser";
	String INTERFACE_ID_DRAG_DROP_INSERT = "appzillonInsertDragDrop";
	String INTERFACE_ID_DRAG_DROP_UPDATE = "appzillonUpdateDragDrop";
	String INTERFACE_ID_DRAG_DROP_DELETE = "appzillonDeleteDragDrop";
	String INTERFACE_ID_DRAG_DROP_SEARCH = "appzillonSearchDragDrop";
	String ACCESS_TYPE_ALLOWED = "A";

	String DENIED_CONTROL_ROLE = "DENIEDCNTRLROLE";
	String ALLOWED_CONTROL_ROLE = "ALLOWEDCNTRLROLE";
	String DENIED_SCREEN_ROLE = "DENIEDSCRNROLE";
	String ALLOWED_SCREEN_ROLE = "ALLOWEDSCRNROLE";
	String DENIED_INTERFACE_ROLE = "DENIEDINTFROLE";
	String ALLOWED_INTFERFACE_ROLE = "ALLOWEDINTFROLE";
	String SERVICE_TXN_LOGGING_SERVICE = "LoggingService";
	String APPZILLON_CHECK_SERVER_RESPONSE = "serverStatus";
	String INTERFACE_ID_CHECK_SERVER = "appzillonCheckServer";

	String A_TO_Z_a_TO_z = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
	String A_TO_Z_a_TO_z_0_9 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
	String ZERO_TO_NINE = "0123456789";
	String OTP_NUMERIC = "NUMERIC";
	String OTP_ALPHA_NUMERIC = "ALPHANUMERIC";
	String OTP_ALPHA = "ALPHA";
	String OTP_DUMMY = "DUMMY";

	String SCREEN_ALLOWED="screenAllowed";
	String INTERFACE_ALLOWED="interfaceAllowed";
	String CONTROL_ALLOWED="controlAllowed";
	String MESSAGE_CONTROL_ID="controlId";
	String CONTROL_IDS="controlIds";
	String USER_ACCESS_APPS="userAccessApps";
	String ALLOWED_APP_ID="allowedAppId";

	// Response Body status
	String RESP_BODY_STATUS_SUCCESS = "Y";
	String RESP_BODY_STATUS_ERROR = "N";
	boolean BOOLEAN_TRUE = true;
	boolean BOOLEAN_FALSE = false;

	//Codec Constants
	String MYSQL_CODEC_REQUIRED = "MYSQLCODECREQUIRED";
	String ORACLE_CODEC_REQUIRED = "ORACLECODECREQUIRED";
	String PERCENT_CODEC_REQUIRED = "PERCENTCODECREQUIRED";
	String PUSHBACK_STRING_REQUIRED = "PUSHBACKSTRINGREQUIRED";
	String HTML_CODEC_REQUIRED = "HTMLENTITYCODECREQUIRED";
	String XML_CODEC_REQUIRED = "XMLENTITYCODECREQUIRED";
	String JS_CODEC_REQUIRED = "JAVASCRIPTCODECREQUIRED";
	String MYSQL_CODEC = "MySQLCodec";
	String ORACLE_CODEC = "OracleCodec";
	String PERCENT_CODEC = "PercentCodec";
	String PUSHBACK_STRING = "PushbackString";
	String HTML_CODEC = "HTMLEntityCodec";
	String XML_CODEC = "XMLEntityCodec";
	String JS_CODEC = "JavaScriptCodec";
	String MESSAGE_HEADER_LOCATION = "location";
	String LATITUDE="latitude";
	String LONGITUDE ="longitude";
	String SUBLOCALITY = "sublocality";
	String ADMIN_AREA_LVL_1 = "admin_area_lvl_1";
	String ADMIN_AREA_LVL_2 ="admin_area_lvl_2";
	String COUNTRY = "country";
	String FORAMATTED_ADDRESS="formattedAddress";
	String DEFAULT_FORMATTED_ADDRESS="Address Not Available";
	String ACCESS_DATE = "accessDate";   
	String START_TM = "stTm";
	String END_TM = "endTm";
	String TOTAL_TIME = "totalTime";
	String QUERY_STRING = "QUERYSTRING";

	//MicroApps Changes
	String INTERFACE_ID_GET_QUERY_DESIGNER_DATA = "appzillonGetQueryDesignerData";
	String APPZILLON_ROOT_GET_QUERYDESIGNER_REQUEST = "appzillonGetQueryDesignerDataRequest";
	String APPZILLON_ROOT_GET_QUERYDESIGNER_RESPONSE = "appzillonGetQueryDesignerDataResponse";
	String SERVICE_CUSTOMIZER="customizerservice";
	String INTERFACE_ID_DEVICE_GRP_QUERY="appzillonDeviceGrpQuery";
	String APPZILLON_ROOT_DEVICEGRPQUERY_REQUEST="appzillonDeviceGrpQueryRequest";
	String APPZILLON_ROOT_DEVICEGRPQUERY_RESPONSE="appzillonDeviceGrpQueryResponse";
	String INTERFACE_ID_APP_SCREEN_QUERY ="appzillonAppScreensQuery";
	String APPZILLON_ROOT_APPSCREENQUERY_REQUEST ="appzillonAppScreensQueryRequest";
	String APPZILLON_ROOT_APPSCREENQUERY_RESPONSE ="appzillonAppScreensQueryResponse";
	String LAYOUT_ID = "layoutId";
	String INTERFACE_ID_SAVE_CUSTOMIZATION_DATA = "appzillonSaveCustomizationData";
	String APPZILLON_ROOT_SAVE_CUSTOMIZATION_DATA_REQUEST = "appzillonSaveCustomizationDataRequest";
	String APPZILLON_ROOT_SAVE_CUSTOMIZATION_DATA_RESPONSE = "appzillonSaveCustomizationDataResponse";
	String CUSTOME_DESIGN = "CurrentDesign";
	String DESIGN_RECEIVERS = "DesignReceivers";
	String DESIGN_ID = "designId";
	String CHILD_ID = "childId";
	String CHILD_SEQ = "childSeq";
	String SCREEN_ID = "screenId";
	String TEMPLATE_ID ="templateId";
	String DESIGN_NAME ="designName";
	String DESIGN_ICON ="designIcon";
	String MICRO_APP_ID ="microAppId";
	String MICRO_APP_NAME ="microAppName";
	String MICRO_APP_ICON= "microAppIcon";
	String MICRO_APP_TYPE = "microAppType";
	String NAVIGATOR_ID ="navigatorId";
	String NAVIGATOR_NAME ="navigatorName";
	String NAVIGATOR_ICON = "navigatorIcon";
	String WIDGET_ID ="widgetId";
	String WIDGET_NAME ="widgetName";
	String WIDGET_ICON ="widgetIcon";
	String SCREEN_NAME ="screenName";
	String DEVICE_DESC ="deviceDesc";
	String HEIGHT = "height";
	String WIDTH ="width";
	String ORIENTATION ="orientation";
	String DEVICE_GROUPS = "DeviceGroups";
	String APP_SCREENS = "AppScreens";
	String SCREEN_DESIGNS ="ScreenDesigns";
	String CURRENT_DESIGNS="CurrentDesign";
	String MICRO_APPS = "Microapps";
	String NAVIGATORS = "Navigators";
	String WIDGETS = "Widgets";
	String ACTIVE = "ACTIVE";
	String INTERFACE_ID_GET_CUSTOMIZER_DETAILS = "appzillonGetCustomizerDetails";
	String APPZILLON_ROOT_GET_CUSTOMIZER_DETAILS_REQUEST = "appzillonGetCustomizerDetailsRequest";
	String APPZILLON_ROOT_GET_CUSTOMIZER_DETAILS_RESPONSE = "appzillonGetCustomizerDetailsResponse";
	String CUSTOMIZER="customizer";
	String ISMODIFIED="isModified";
	String TEMLT="template";
	String CONTAINERS="containers";
	String MICROAPPS="microApps";
	String CALLFORMS="callForms";
	String SEQUENCE = "sequence";
	String INTERFACE_ID_SAVE_APPACCESS = "appzillonSaveAppAccess";
	String APPZILLON_ROOT_SAVE_APPACCESS_REQUEST = "appzillonSaveAppAccessRequest";
	String APPZILLON_ROOT_SAVE_APPACCESS_RESPONSE = "appzillonSaveAppAccessResponse";
	String APP_ACCESS="appAccess";
	String SERVICE_MICROAPP = "MicroAppTxnService";
	String SERVICE_SAVE_MICROAPPTXNDETAILS = "SaveMicroAppTxnDtls";
	String SERVICE_UPDATE_MICROAPPTXNDETAILS = "UpdateMicroAppTxnDtls";
	String SERVICE_FETCH_MICROAPPTXNDETAILS = "FetchMicroAppTxnDtls";
	String CUSTOMER_ID = "customerId";
	String AMOUNT = "amount";
	String TXN_TYPE = "txnType";
	String TXN_REF = "txnRef";
	String TXN_REF_NO = "txnRefNo";
	String UPDATE_TS = "updateTs";
	String CREATION_TS = "creationTs";
	String COMPLETION_TS = "completionTs";
	String SAVE_MICROAPP_TXN_DETAILS = "saveMicroAppTxnDtls";
	String UPDATE_MICROAPP_TXN_DETAILS = "updateMicroApptxnDtls";
	String FETCH_MICROAPP_TXN_DETAILS = "fetchMicroAppTxnDtls";
	String SERVICE_TRACK_LOCATION = "TrackLocationService";
	String INTERFACE_ID_TRACK_LOCATION = "appzillonTrackLocation";
	String APPZILLON_ROOT_TRACK_LOCATION_REQUEST = "appzillonTrackLocationRequest";
	String APPZILLON_ROOT_TRACK_LOCATION_RESPONSE = "appzillonTrackLocationResponse";
	//SESSION_STORAGE
	String APPZILLON_SESSION_STORAGE_SERVICE = "SessionStorageService";
	String SERVICE_SAVE_OR_UPDATE_SESSION_STORAGE = "appzillonSaveorUpdateSssionStorage";
	String SERVICE_CHECK_AND_UPDATE_COOKIE = "appzillonCheckAndUpdateCookie";
	String SERVICE_TYPE_DELETE_SESSION_STORAGE = "appzillonDeleteSessionStorage";
	String SERVICE_GET_USER_SESSION_STORAGE = "appzillonGetSessionStorage";
	String SERVICE_GET_USER_SESSION_STORAGE_ARRAY = "appzillonGetSessionStorageArray";
	String REQUEST_DATA = "userDataFromService";
	String USER_DATA_LOG_KEY = "userDataLogKey";
	String USER_DATA_KEY = "key";
	String USER_DATA_VALUE = "value";
	String SESSION_VALUES_ARRAY = "sessionArrayVals";
	//Captcha Changes
	String CAPTCHA_STRING = "captchaString";
	String AUDIO_CAPTCHA="audioCaptcha";
	String TEXT="TEXT";
	String AUDIO="AUDIO";
	String CAPTCHA_REF = "captchaRef";
	String CAPTCHA_STATUS = "captchaStatus";
	String PERSIST_CAPTCHA = "persistCaptcha";  
	String VALIDATE_CAPTCHA = "validateCaptcha";
	String INTERFACE_ID_GENERATE_CAPTCHA = "appzillonGenerateCaptcha";
	String FETCH_CAPTCHA_MAP = "fetchCaptchaMap";
	String APPZILLON_ROOT_GENERATE_CAPTCHA_REQUEST = "appzillonGenerateCaptchaRequest";
	String APPZILLON_ROOT_GENERATE_CAPTCHA_RESPONSE = "appzillonGenerateCaptchaResponse";
	String PERSIST_CAPTCHA_REQUEST = "persistCaptchaRequest";
	String BEAN_SMS_CAPTCHA_GENERATE = "captchaGenerateHandler";
	String BEAN_SMS_CAPTCHA_PROPERTIES="iCaptchaPropertiesImpl";
	String VALIDATE_CAPTCHA_RESPONSE = "validateCaptchaResponse";
	String SERVICE_CAPTCHA = "CaptchaService";
	String SERVICE_INTERFACE_MASTER = "InterfaceMasterService";
	String SERVICE_SERVER_PROPERTIES = "ServerPropertiesService";

	String SERVICE_CONVERSATIONAL_UI = "ConversationalUIService";
	String INTERFACE_ID_GET_CNVUI_WELCOME_MSG = "getCnvUIWelcomeMsg";
	String INTERFACE_ID_GET_FIRST_CNVUI_DLG = "getFirstCnvUIDlg";
	String INTERFACE_ID_GET_CNVUI_DLG = "getCnvUIDlg";
	String INTERFACE_ID_PROCESS_NLP_DATA= "processNLPData";
	String APPZILLON_ROOT_GET_CNVUI_WELCOME_MSG_REQUEST = "getCnvUIWelcomeMsgRequest";
	String APPZILLON_ROOT_GET_CNVUI_WELCOME_MSG_RESPONSE = "getCnvUIWelcomeMsgResponse";
	String APPZILLON_ROOT_GET_FIRST_CNVUI_DLG_REQUEST = "getFirstCnvUIDlgRequest";
	String APPZILLON_ROOT_GET_FIRST_CNVUI_DLG_RESPONSE = "getFirstCnvUIDlgResponse";
	String APPZILLON_CNVUI_ID = "Id";
	String APPZILLON_NLP_CNVUI_ID = "cnvUIId";
	String APPZILLON_ROOT_GET_CNVUI_DLG_REQUEST = "getCnvUIDlgRequest";
	String APPZILLON_ROOT_GET_CNVUI_DLG_RESPONSE = "getCnvUIDlgResponse";
	String INTERFACE_TYPE_CNVUI = "CNVUI";
	String INTERFACE_TYPE_NLP = "NLP";
	String CNVUI_RULES_BEAN = "CnvUIRules";
	String SCREEN_DEF = "screenDef";
	String NEXT_DLG_ID = "nextDlgId";
	String DLG_DESC = "dlgDesc";
	String SCREEN_HTML = "screenHtml";
	String SCREEN_DETAILS = "screenDetails";
	String DLG_ID = "dlgId";
	String CNVUI_SCREEN_DATA = "screenData";
	String SERVICES_BEAN_CNVUI_IMPL = "ConversationalUIImpl";
	String DLG_ID_FROM_RULE_BEAN = "dlgIdFromRuleBean";
	String SERVICE_BEAN_NLP_IMPL = "NLPImpl";
	String CNVUI_LOG_TRANSACTION = "cnvUILogTransaction";
	String RESP_DLG_ID = "respDlgId";
	String PROCESS_NLP_DATA_REQUEST = "processNLPDataRequest";
	String PROCESS_NLP_DATA_RESPONSE = "processNLPDataResponse";
	String SERVICE_BEAN_PROCESS_NLP = "ProcessNLP";

	// interface definition
	String INTERFACE_ID_GET_INTF_DEF = "appzillonGetIntfDef";
	String APPZILLON_ROOT_GET_INTF_DEF_REQUEST = "appzillonGetIntfDefRequest";
	String APPZILLON_ROOT_GET_INTF_DEF_RESPONSE = "appzillonGetIntfDefResponse";
	String INTERFACE_DEFINITION = "interfaceDef";
	//csNonce
	String CS_NONCE_DETAILS = "csNonceDetails";
	String CLIENT_NONCE = "clientNonce";
	String SERVER_NONCE = "serverNonce";
	String SESSION_TOKEN = "sessionToken";
	String LOGGER_PREFIX_NONCE = "[NonceServcie] =>";
	String SERVICE_APP_MASTER = "AppMasterService";
	String WEB_SESSION = "webSession";
	String NONCE_VERIFICATION = "NonceVerification";
	String QOP = "appzillonQop";
	String HTTP_ERROR_BODY = "httpErrorBody";
	String INTERFACE_ID_GET_APP_SEC_TOKENS = "appzillonGetAppSecTokens";
	String APPZILLON_ROOT_GET_APP_SEC_TOKENS_REQUEST = "appzillonGetAppSecTokensRequest";
	String APPZILLON_ROOT_GET_APP_SEC_TOKENS_RESPONSE = "appzillonGetAppSecTokensResponse";
	String SAFE_TOKEN = "safeToken";
	String REQUEST_PAYLOAD="payLoad";
	String SERVICE_PURGE_NONCE = "PurgeNonce";
	String ENCRYPTION_FLAG = "PAYLOADENCRYPTIONREQ";
	String ENCRYPTION_KEY_FILENAME= "ENCRYPTIONKEYFILENAME";
	String LINE_SEPARATOR = "line.separator";
	String APZRICT = "APZRICT";
	String APZCNTR = "APZCNTR";
	String RICT = "RICT";
	String APPZILLON_ERROR_CODE = "errorCode";
	String PAYLOAD_ENCRYPTION_ERROR_CODE = "APZ-CNT-330";
	String SALT = "Salt: ";
	String DOLLAR="$";
	String APPZILLON_SAFE_KEY = "APPZILLONSAFEKEY";
	String NOTIF="NOTIF";
	String REPLAY_REQUEST_REQUIRED ="REPLAYREQ";//used to disable full security
	String CAMEL_COMPONENT_HTTP = "http";
	String CLEAR_SERVER_NONCES = "clearServerNonces";
	String REPLAY_ATTACK_CHECK = "CHECKNONCE";
	//proxy settings for push notification
	String PROXY_HOST = "PROXYHOST";
	String PROXY_PORT = "PROXYPORT";
	String PROXY_TYPE = "PROXYTYPE";
	String PROXY_USER = "PROXYUSER";
	String PROXY_PASSWORD = "PROXYPASSWORD";
	String NONPROXYHOSTS = "NONPROXYHOSTS";

	// Workflow Constants
	String WORKFLOW_ID = "workflowId";
	String WORKFLOW_REF_NO = "workflowRefNo";
	String WORKFLOW_SEQ_NO = "workflowSeqNo";
	String TASK_DATA = "taskData";
	String WORKFLOW_STATUS_STARTED = "STARTED";
	String WORKFLOW_STATUS_SAVED = "SAVED";
	String WORKFLOW_STATUS_WIP = "WIP";
	String WORKFLOW_STATUS_NEXT = "NEXT";
	String WORKFLOW_STATUS_PREV = "PREV";
	String WORKFLOW_STATUS_ASSIGNED = "ASSIGNED";
	String WORKFLOW_STATUS_REASSIGNED = "REASSIGNED";
	String WORKFLOW_STATUS_ACQUIRED = "ACQUIRED";
	String WORKFLOW_STATUS_UNASSIGNED = "UNASSIGNED";

	String WORKFLOW_STATUS_TERMINATED = "TERMINATED";
	String WORKFLOW_STATUS_REJECTED = "REJECTED";
	String WORKFLOW_STAGE_ID = "stageId";
	String WORKFLOW_STAGE_TYPE = "stageType";
	String WORKFLOW_SCREEN_ID = "screenID";

	String WORKFLOW_STATUS_PENDING = "PENDING";
	String WORKFLOW_CUSTOM_FIELD_1 = "customField1";
	String WORKFLOW_CUSTOM_FIELD_2 = "customField2";
	String WORKFLOW_CUSTOM_FIELD_3 = "customField3";
	String WORKFLOW_CUSTOM_FIELD_4 = "customField4";
	String WORKFLOW_CUSTOM_FIELD_5 = "customField5";
	String SERVICE_WORKFLOW_START = "WorkflowStartService";
	String WORKFLOW_ACQUIRE_RESPONSE = "workflowAcquireResponse";
	String WORKFLOW_UNASSIGN_RESPONSE= "workflowUnassignResponse";
	String WORKFLOW_ASSIGN_RESPONSE = "workflowAssignResponse";
	String WORKFLOW_RE_ASSIGN_RESPONSE = "workflowReassignResponse";
	String APPZILLON_WORKFLOW_ID = "workflowId";
	String APPZILLON_WORKFLOW_REF_NO = "workflowRefNo";

	String APPZILLON_WORKFLOW_SEQ_NO = "workflowSeqNo";
	String WORKFLOW_STATUS_COMPLETED = "COMPLETED";
	String WORKFLOW_STATUS_SKIPPED = "SKIPPED";
	String WORKFLOW_REMARKS = "remarks";
	String WORKFLOW_TASK_DATA = "taskData";
	String WORKFLOW_LINKED_STAGE_TYPE_NEXT = "N";
	String WORKFLOW_LINKED_STAGE_TYPE_PREV = "P";

	//cookies
	String COOKIE_AGE = "COOKIEAGE";
	String KEEP_ME_SIGNED_IN_ENABLED = "KEEPMESIGNEDIN";
	String SELECTOR = "selector";
	String KEEP_ME_SIGNED_IN_FLAG = "keepMeSignedIn";

	//large data records
	String TXN_LOG_PAYLOAD_REQUEST = "REQUEST";
	String TXN_LOG_PAYLOAD_RESPONSE = "RESPONSE";
	String TXN_LOG_PAYLOAD_BOTH = "BOTH";
	String TXN_LOG_PAYLOAD_NONE = "NONE";
	String SERVICE_DELETE_LD_RECS = "ServiceDeleteLdRecs";
	String SERVICE_LD_RECS = "LdRecsService";
	
	//app accessToken 
	String BASIC_AUTH = "Basic";
	String BEARER_TOKEN = "Bearer";
	String INTERACE_ID_GET_USER_APPACCESS_TOKEN = "appzillonGetUserAppAccessToken";
	String VALIDATE_USER_APP_ACCESS_TOKEN = "validateUserAppAccessToken";
	String SERVICE_GET_USER_APP_ACCESS_TOKEN = "GetUserAppAccessToken";
	String EXTERNAL_USER_LVL = "5";
	String USER_APP_ACCESS_TOKEN = "userAppAccessToken";
	String APPZILLON_ROOT_GET_USER_APP_ACCESS_TOKEN_REQ = "appzillonGetUserAppAccessTokenRequest";
	String APPZILLON_ROOT_GET_USER_APP_ACCESS_TOKEN_RES = "appzillonGetUserAppAccessTokenResponse";
	String USER_LVL = "userLvl";
	
	String LOGGER_PREFIX_CITI = "[CitiServcie] =>";
	String INTERFACE_ID_PARSE_META_JSON="apzParseMetaJSON";
	String INTERFACE_ID_PARSE_PRODUCT_JSON="apzParseProductJSON";
	String INTERFACE_ID_PARSE_WIDGET_JSON="apzParseWidgetJSON";
	String INTERFACE_ID_INSERT_HTML_JSON="apzPersistHTMLInfo";
	String INTERACE_ID_RELOAD_LOGGER = "appzillonReloadLogger";
	String INTERACE_ID_RELOAD_SERVER_PROPERTIES = "reloadServerProperties";
	String IOS_BUNDLE_ID = "IOSBUNDLEID";
	
	//Web push Notification 
			
	 String WEB_NOTIFICATION_CLICK_ACTION = "clickAction";
	 String WEB_NOTIFICATION_SERVER_KEY="WEBNOTIFICATIONSERVERKEY";
	 String WEB_NOTIFICATION_RESULTS="results";	
	 String WEB_NOTIFICATION_BODY="body";
	 String WEB_NOTIFICATION_ICON="icon";
	 String WEB_NOTIFICATION_REGISTRATION_ID="registration_ids";
	 String UNSUPPORTED_ENCODING_EXCEPTION="UnsupportedEncodingException";
	 String WEB_NOTIFICATION_URL="WEBNOTIFICATIONURL";
     String WEB_NOTIFICATION_METHOD="WEBNOTIFICATIONMETHOD";
     String WEB_NOTIFICATION_CONTENT_TYPE="WEBNOTIFICATIONCONTENTTYPE";
     String CONTENT_TYPE="Content-Type";
     String AUTHORIZATION="Authorization";
     String OTP_EXPIRY_TS = "OTPEXPIRY";
     
     String OTPSEND_FILE_TEMPLATE = "OTPSend_";
     String EMAIL = "_EMAIL";
     String MSG = "_MSG";
     String SPRING = "spring";
     String CAMEL_CONTEXT_XML = "app-camel-context.xml";
     String SMS_SPRING_XML = "SMS-Spring.xml";
     String NOTIFICATION_XML = "Notification-Spring.xml";
     String SMS_SERVICES = "SMS-Services";
     String LOG_LEVEL = "LOGLEVEL";
     String LOG4J_FILTER_KEY = "logRouter";
     String INTERFACE_ID_CREATE_TENANT = "appzillonCreateTenant";
     String APPZILLON_ROOT_CREATE_TENANT_REQUEST = "appzilloncreateTenantRequest";
     String APPZILLON_ROOT_CREATE_TENANT_RESPONSE = "appzilloncreateTenantResponse";
     String ISO ="iso";
     String STATIC_SQL_DATA = "Staticdata";
     String MULTI_TENANT = "MULTITENANT";
     String SERVICE_INTERFACE_MASTER_UPDATE = "IntfMastertableUpdate";
     String JNDI_DATA_SOURCE = "DATASOURCE";
	String APZ_VARIABLE = "${APZ:";
	String ENV_VARIABLE = "${env:";
	String SYSTEM_VARIABLE = "${sys:";
	String ENV_FILE_NAME = "ENVFILENAME";
	String APP_VERSION = "appVersion";
	String UPDATE_APP_VERSION = "updateAppVersion";
	String UPDATE_ACTION = "updateAction";
	String HAUWEI_MSG_SERVER = "HUAWEI";
	String NOTIF_MSG_SERVER = "notifMsgServer";
	String HUAWEI_SUCCESS_RESPONSE_CODE = "80000000";
	String NOTIFICATION_CODE = "notification_code";
	String IMAGE_URL = "image_url";

	//azure ad changes
	String AZURE_AD_AUTH_ENABLED="AZUREADAUTHREQ";
	String AAD_SCOPES = "openid offline_access {client_id}";
	String AAD_SIGN_IN_POLICY = "AAD_SIGNINPOLICY";
	String AAD_AUTHORITY = "aad_authority";
	String AAD_SECRET = "AAD_SECRET";
	String AAD_CLIENT_ID = "AAD_CLIENTID";
	String AAD_APP_REDIRECT_URI = "AAD_REDIRECTURI";
	String AAD_ENDPOINT_TOKEN = "https://{domain}.b2clogin.com/{domain}.onmicrosoft.com/{policy}/oauth2/v2.0/token";
	String SERVICE_AZURE_AUTHENTICATION = "AzureAuthenticationService";
	String FETCH_AZURE_TOKENS = "appzillonFetchAzureTokens";
	String PERSIST_OR_UPDATE_AZURE_TOKENS = "appzillonPersistAOrUpdateAzureTokens";
	String AZURE_GRANT_TYPE_AUTH_CODE = "authorization_code";
	String AZURE_GRANT_TYPE_REFRESH_TOKEN = "refresh_token";
	String CODE_TYPE_AUTH = "auth_code";
	String CODE_TYPE_REFRESH = "refresh_code";
	String AAD_DOMAIN_NAME = "AAD_DOMAIN_NAME";
	String AUTH_CODE = "code";
	String REFRESH_TOKEN = "refresh_token";

	String MESSAGE_HEADER_AUTH_CODE = "authCode";
	String AAD_REDIRECT_URI = "redirect_uri";

	String ID_TOKEN = "id_token";
	String ACCESS_TOKEN_TIME_OUT = "expires_in";
	String ACCESS_TOKEN_EXPIRES_ON = "expires_on";
	String ID_TOKEN_EXPIRY_TIMEOUT = "id_token_expires_in";
	String ACCESS_TOKEN_GENERATED_ON = "not_before";
	String REFRESH_TOKEN_TIMEOUT = "refresh_token_expires_in";
	String TOKEN_TYPE = "token_type";
	//String AZURE_AD = "AzureAD";
	//changes end
    String UPDATE_FAILED_PWD_COUNT = "updateFailedChangePwdCount";
    String CHECK_USER_LOCKED = "checkUserLocked";

	String THIRD_PARTY_AUTH_ENABLED="THIRDPARTYAUTHENABLED";

	String GRANT_TYPE_REFRESH_TOKEN = "refresh_token";
	String MESSAGE_HEADER_AUTH_TOKEN = "authToken";
	String UPDATE_AUTH_TOKEN = "updateAuthToken";

	String LAST_NAME = "lastName";
	String AUTH_PROVIDER="authProvider";
	String AUTH_TYPE="authType";
}

